import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

/**
 * ESLint flat config.
 *
 * Previously this was a SINGLE block matching `**\/*.{ts,tsx}`, which applied
 * browser globals and `no-console: error` uniformly to three environments that
 * have nothing in common:
 *
 *   - `src/**`                 browser, has the `logger` observability layer
 *   - `supabase/functions/**`  Deno, CANNOT import `@/lib/observability`
 *   - `*.config.ts`            Node, legitimately uses `require()`
 *
 * The result was ~16 errors that were not defects at all — an edge function
 * writing to `console.error` was flagged even though the Supabase dashboard's
 * function-log panel reads nothing else, and `tailwind.config.ts` was flagged
 * for the `require()` its plugin API expects. Noise like that trains people to
 * ignore lint output, which is how the real violations survive.
 *
 * The environment-specific blocks below fix that. Each override states why it
 * exists; none of them relaxes a rule where the stricter behaviour is
 * achievable.
 */
export default tseslint.config(
  {
    ignores: [
      "dist",
      "dev-dist",
      "coverage",
      "playwright-report",
      "test-results",
      // Generated by `supabase gen types` — never hand-edited, so linting it
      // produces noise no one can action.
      "src/integrations/supabase/types.ts",
    ],
  },

  // ── Base: browser application code ────────────────────────────────────────
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": "off",
      // Hard rule for src/**: every log must go through `logger` from
      // `@/lib/observability`, which scrubs PII and buffers offline. A raw
      // console call bypasses both.
      "no-console": "error",
    },
  },

  // ── shadcn/ui primitives (generated) ──────────────────────────────────────
  {
    files: ["src/components/ui/**/*.{ts,tsx}"],
    rules: {
      // These files are shadcn-generated and the project convention is not to
      // hand-edit them (wrap them in feature components instead), so a lint
      // rule that demands editing them is a rule that will simply be ignored.
      //
      // The pattern being flagged is shadcn's idiomatic named props alias:
      //     interface CommandDialogProps extends DialogProps {}
      //     export interface TextareaProps extends React.TextareaHTMLAttributes<...> {}
      // An empty interface extending exactly one type is a deliberate, useful
      // alias — it gives the component a named, externally-extensible props
      // type.
      //
      // `allowInterfaces: "with-single-extends"` is used rather than switching
      // the rule off: a genuinely empty `interface Foo {}` or `type Foo = {}`
      // is still an error here, because those really are mistakes.
      "@typescript-eslint/no-empty-object-type": [
        "error",
        { allowInterfaces: "with-single-extends" },
      ],
    },
  },

  // ── Supabase edge functions (Deno) ────────────────────────────────────────
  {
    files: ["supabase/functions/**/*.ts"],
    languageOptions: {
      // The `globals` package shipped here has no `deno` preset, so the
      // runtime's one global is declared explicitly.
      globals: {
        Deno: "readonly",
        EdgeRuntime: "readonly",
      },
    },
    rules: {
      // `console` is the ONLY log sink available to an edge function: it runs
      // in Deno, cannot import `@/lib/observability`, and the Supabase
      // dashboard's function-log panel surfaces nothing else. Every function
      // here already routes through an inlined structured logger
      // (`_shared/edge-logger.ts`, or an inlined copy where the dashboard
      // bundler can't resolve `../_shared/*`) whose final act is a
      // `console.*` write. Flagging that is a false positive, and suppressing
      // it per-call-site — as this repo had started doing — just scatters
      // `eslint-disable` comments through the logging layer.
      "no-console": "off",
    },
  },

  // ── Build / tooling config files (Node) ───────────────────────────────────
  {
    files: ["*.config.{ts,js,mjs}", "scripts/**/*.{ts,js,mjs}"],
    languageOptions: {
      globals: globals.node,
    },
    rules: {
      // `tailwind.config.ts` uses `require()` because Tailwind's plugin API is
      // CommonJS; converting it to ESM import would change plugin resolution
      // for no benefit. These files are never shipped to the browser.
      "@typescript-eslint/no-require-imports": "off",
      "no-console": "off",
    },
  },

  // ── Vercel serverless functions (Node runtime, not the browser) ───────────
  {
    files: ["api/**/*.ts"],
    languageOptions: {
      globals: globals.node,
    },
    rules: {
      // Same reasoning as edge functions: these run server-side, cannot reach
      // the browser observability layer, and Vercel's function logs read
      // stdout/stderr.
      "no-console": "off",
    },
  },
);
