import SiteHeader from "@/components/SiteHeader";

/**
 * GDPR Notice — for users in the EU/EEA, UK, and Switzerland (and any user
 * exercising equivalent international rights).
 *
 * Cross-referenced with our main Privacy Policy at /privacy. Where Indian and
 * GDPR provisions overlap, we apply the stricter standard.
 *
 * Article references throughout are to the EU GDPR (Regulation (EU) 2016/679)
 * with equivalent UK GDPR provisions implied where applicable.
 */

const sections = [
  {
    title: "1. Who this notice applies to",
    body: `This Notice supplements our main Privacy Policy at /privacy for individuals whose personal data is protected by:

• The EU General Data Protection Regulation (Regulation (EU) 2016/679) — for data subjects in the European Economic Area.
• The UK GDPR and the Data Protection Act 2018 — for data subjects in the United Kingdom.
• The Federal Act on Data Protection (FADP), as revised — for data subjects in Switzerland.
• Any other jurisdiction (Brazil's LGPD, California's CCPA/CPRA, South Africa's POPIA, etc.) to the extent it provides equivalent rights — we honour comparable rights on a global basis as a matter of policy.

If you are an Indian Data Principal, our Privacy Policy and the rights it describes under DPDPA 2023 will be your primary reference. This Notice fills gaps for users covered by GDPR and similar regimes.`,
  },
  {
    title: "2. Our role — Controller and Processor",
    body: `For personal data we collect directly from you (e.g., when you create an account, browse the platform, or contact us) — Illuxus Technologies Private Limited is the Data Controller. We determine the purposes and means of processing.

For personal data uploaded or generated by event organisers in connection with their events (e.g., guest lists they import, registration questions they design, attendee data they download) — the organiser is the Data Controller and Illuxus is the Data Processor. Our processing is governed by our standard Data Processing Addendum.

A complete and up-to-date list of our sub-processors is available in Section 5 of the Privacy Policy and on request at privacy@illuxus.com.`,
  },
  {
    title: "3. Lawful bases under GDPR Article 6",
    body: `We process personal data on one or more of the following lawful bases set out in Article 6(1) GDPR:

(a) Consent (Art. 6(1)(a)) — marketing emails, optional profile fields, precise location, Analytics/Marketing cookies, special-category data (with Art. 9 condition).

(b) Performance of a contract (Art. 6(1)(b)) — account creation, ticket purchase, ticket delivery, support.

(c) Compliance with a legal obligation (Art. 6(1)(c)) — tax records, anti-money-laundering, statutory disclosures, lawful orders.

(d) Vital interest (Art. 6(1)(d)) — emergency medical contact disclosure at in-person events.

(e) Public task (Art. 6(1)(e)) — generally not relied upon, except where we cooperate with an authority performing public functions (lawful orders).

(f) Legitimate interests (Art. 6(1)(f)) — fraud prevention, security, network integrity, internal analytics, product improvement, defending legal claims. We balance our interests against your rights and freedoms and document the balancing assessment.

Where consent is the basis, you have the right to withdraw it at any time without affecting the lawfulness of prior processing (Art. 7(3)).`,
  },
  {
    title: "4. Categories of data subjects",
    body: `We process personal data about the following categories of data subjects:

• Account holders — organisers, attendees, speakers, sponsors, and Illuxus employees with platform access.
• Visitors — anyone browsing public pages on illuxus.com.
• Contacts — recipients of organiser-sent communications who may not themselves have accounts.
• Third-party representatives — auditors, advisors, vendor representatives interacting with Illuxus.

We do not knowingly process personal data of minors below the digital-age-of-consent applicable in their country (see Section 14).`,
  },
  {
    title: "5. Categories of personal data",
    body: `In GDPR terms, the categories of personal data we process are:

• Identity data — name, gender (optional), date of birth, profile picture, government-issued ID for organiser KYC.
• Contact data — email, phone, postal address.
• Account data — username, password hash, MFA secrets, OAuth tokens.
• Transactional data — ticket purchases, refunds, settlements, invoice numbers.
• Profile data — job title, employer, bio, social links, dietary preferences (Art. 9 special-category — only with explicit consent), accessibility requirements.
• Behavioural data — pages visited, features used, click events.
• Technical data — IP, device, browser, OS, screen resolution.
• Location data — approximate (from IP) or precise (only with consent).
• Communications data — messages with organisers, support tickets.
• Marketing preferences — opt-in status per channel.

Special categories under Article 9 — dietary preferences may reveal religious belief or health information (e.g., kosher, halal, vegan, allergens). Accessibility requirements may reveal health information. We process such data only with explicit consent under Article 9(2)(a). Biometric data is not collected.`,
  },
  {
    title: "6. Data subject rights (Articles 15–22)",
    body: `If you are protected by the GDPR, you have the following rights:

(a) Right of access (Art. 15) — confirm whether we process your personal data, and if so receive a copy and information about the processing.

(b) Right to rectification (Art. 16) — have inaccurate or incomplete personal data corrected.

(c) Right to erasure / "right to be forgotten" (Art. 17) — have personal data deleted where one of the Article 17(1) conditions is met (no longer necessary, consent withdrawn, unlawful processing, legal obligation, child data). Subject to Article 17(3) exceptions (freedom of expression, legal obligation, public interest, defending legal claims).

(d) Right to restriction of processing (Art. 18) — temporarily limit how we process your data, for example while we verify a rectification request.

(e) Right to data portability (Art. 20) — receive personal data you provided in a structured, commonly used, machine-readable format, and transmit it to another controller. We provide JSON and CSV exports.

(f) Right to object (Art. 21) — object to processing based on legitimate interest or for direct marketing. An objection to direct marketing is absolute and we will stop without question.

(g) Rights related to automated decision-making and profiling (Art. 22) — not be subject to decisions based solely on automated processing producing legal or similarly significant effects. We do not conduct such automated decision-making; see Section 13.

(h) Right to withdraw consent (Art. 7(3)) — withdraw consent at any time without retroactive effect.

(i) Right to lodge a complaint with a supervisory authority (Art. 77) — see Section 19.

(j) Right not to be subject to discrimination — exercising any of the above rights will not result in adverse treatment.`,
  },
  {
    title: "7. How to exercise your rights",
    body: `To exercise any of your rights:

• Online — Settings → Privacy → Data subject requests (signed-in users).
• Email — write to privacy@illuxus.com from the email associated with your account.
• Post — Privacy Office, Illuxus Technologies Private Limited, 4th Floor, Lighthouse Tower, Bandra Kurla Complex, Mumbai – 400 051, Maharashtra, India.

Identity verification — to protect your data, we may ask you to verify your identity (a second-factor challenge, or a confirmation email/SMS, or a copy of an ID matching the account name redacted of unnecessary information).

Response timeline — we respond within 30 calendar days of receipt. For complex or numerous requests we may extend by a further 60 days (Art. 12(3)), with notice and reasons within the original 30-day window.

Cost — there is no fee for exercising your rights. We may charge a reasonable fee, or refuse, in the case of manifestly unfounded or excessive requests (Art. 12(5)).

Authorised agents — you may authorise an agent to act on your behalf. We will verify both the agent's authority and your identity.`,
  },
  {
    title: "8. International transfers (Chapter V)",
    body: `Illuxus is based in India, and some sub-processors are located in the United States, Ireland, the United Kingdom, and other third countries.

For transfers from the EEA / UK / Switzerland to India and onward to third countries, we rely on one or more of the following Chapter V mechanisms:

• EU Standard Contractual Clauses (SCCs) 2021/914 — included in every sub-processor agreement.
• UK International Data Transfer Addendum (IDTA) — for transfers from the UK.
• Swiss FDPIC-approved adaptations to the SCCs — for transfers from Switzerland.
• Adequacy decision — for transfers to jurisdictions designated as adequate by the European Commission or the UK Government (e.g., the EU–US Data Privacy Framework where applicable).
• Supplementary measures — encryption in transit and at rest, pseudonymisation, and access restrictions to mitigate residual risks identified in our Transfer Impact Assessments (post-Schrems II).

A copy of the SCCs and a redacted TIA can be requested at dpo@illuxus.com.`,
  },
  {
    title: "9. Data Protection Officer (DPO)",
    body: `Although our core activities do not yet meet the Article 37(1) thresholds for a mandatory DPO appointment, we have voluntarily designated a Privacy Lead to perform DPO-equivalent functions:

Privacy Lead / DPO contact:
Name: Ananya Iyer
Email: dpo@illuxus.com
Postal: Privacy Office, Illuxus Technologies Private Limited, 4th Floor, Lighthouse Tower, Bandra Kurla Complex, Mumbai – 400 051, Maharashtra, India.

The Privacy Lead is independent, reports to the Board, and is not penalised for performing their tasks. They are your primary contact for all GDPR matters.`,
  },
  {
    title: "10. EU / UK Representative (Article 27)",
    body: `Illuxus does not currently have an establishment in the European Union or the United Kingdom and is not subject to the Article 27 obligation to appoint a Representative because our offering to EU/UK data subjects is not yet at the scale that would trigger it.

If and when our offering to EU/UK data subjects expands to a level that triggers Article 27, we will appoint a Representative and publish their details on this page. In the interim, all GDPR enquiries should be directed to dpo@illuxus.com.`,
  },
  {
    title: "11. Retention",
    body: `We retain personal data only for as long as necessary for the purposes set out in Section 4 of the Privacy Policy. The same retention windows apply to EU/UK data subjects, with the following GDPR-specific clarifications:

• Tax records — 7 years (overriding any deletion request to the extent legally required).
• Marketing consent — until withdrawn plus 3 years (to evidence prior consent under Art. 7(1)).
• Logs of access — 180 days (CERT-In aligned, balanced against minimisation under Art. 5(1)(e)).
• Cookie consent — 12 months.

After retention expires, data is securely deleted, anonymised, or aggregated.`,
  },
  {
    title: "12. Special-category data (Article 9)",
    body: `Where event participation involves data that may be "special category" under Art. 9 — for example, dietary preferences (which may reveal religious belief or health), accessibility requirements (health), or photographs in certain contexts — we rely on Art. 9(2)(a) explicit consent.

We do not collect biometric data for identification purposes. Face recognition at check-in is disabled by default and will only be offered as an opt-in feature where the local supervisory authority has confirmed acceptable safeguards.

We do not process data relating to criminal convictions or offences except where we are required to do so by law (e.g., responding to a court order).`,
  },
  {
    title: "13. Profiling and automated decision-making (Article 22)",
    body: `We use limited profiling, namely:

• Event discovery ranking — personalised based on your activity history. You can switch to a chronological "Latest" view.
• Fraud detection — rule-based scoring; high-risk transactions are routed to a human reviewer who makes the final decision.

None of these constitute "solely automated" decision-making producing legal or similarly significant effects on you within Article 22. A human is always in the loop for adverse decisions (account suspension, refund denial, payout hold).`,
  },
  {
    title: "14. Children (Article 8)",
    body: `Under Article 8(1) GDPR, the default age of digital consent is 16; EU Member States may lower it to 13. The UK has set its age at 13 under the Data Protection Act 2018.

In line with the strictest interpretation across our user base, we treat any user identifying as under 16 as a child for the purposes of consent-based processing, except in the UK where we apply the local age of 13. Verifiable parental or guardian consent is required before consent-based processing of children's data.

We do not target advertising at children, do not behaviourally profile children, and apply the highest privacy defaults to all under-18 accounts (consistent with the UK ICO's Age-Appropriate Design Code).`,
  },
  {
    title: "15. Personal data breach notification (Articles 33–34)",
    body: `In the event of a personal data breach:

• We notify the competent supervisory authority within 72 hours of becoming aware (Art. 33), unless the breach is unlikely to result in a risk to the rights and freedoms of natural persons.
• Where the breach is likely to result in a high risk to the rights and freedoms of natural persons, we communicate the breach to affected data subjects without undue delay (Art. 34), in clear and plain language, describing the nature of the breach, the likely consequences, mitigation steps you can take, and our point of contact.
• We maintain an internal register of all breaches whether notifiable or not.

For EU/UK data subjects, our reporting timeline runs in parallel with the Indian CERT-In 6-hour reporting and DPDPA 72-hour Data Protection Board reporting obligations.`,
  },
  {
    title: "16. Records of processing activities (Article 30)",
    body: `We maintain a Record of Processing Activities ("ROPA") as required by Article 30 GDPR. The ROPA documents, for each processing activity: the controller, the purposes, the categories of data subjects and data, the categories of recipients, transfers to third countries, retention periods, and a general description of the technical and organisational measures applied.

The ROPA is made available to supervisory authorities on request. Selected extracts can be shared with enterprise customers under NDA.`,
  },
  {
    title: "17. Cookies and tracking technologies",
    body: `Cookies and similar technologies are described in our Cookie Policy at /cookies. For EU/UK users, we require explicit opt-in consent before setting non-essential cookies, in compliance with the ePrivacy Directive (2002/58/EC) and PECR.

We honour browser-level Do Not Track (DNT) and Global Privacy Control (GPC) signals as a withdrawal of consent for Analytics and Marketing cookies.`,
  },
  {
    title: "18. Direct marketing",
    body: `We send direct marketing only with your prior, freely-given, specific, and informed opt-in. Every marketing email contains an unsubscribe link in the footer that is processed within 24 hours. SMS and WhatsApp marketing additionally honour reply-STOP.

Under Article 21(2) GDPR, your right to object to direct marketing is absolute — we will not require any reasons.

Organiser-driven marketing — when an organiser uses Illuxus's broadcast feature to email attendees of their event, the organiser is the Controller of that processing and is responsible for the lawful basis. Illuxus enforces a one-click unsubscribe in every such email.`,
  },
  {
    title: "19. Complaints to supervisory authorities (Article 77)",
    body: `You have the right to lodge a complaint with a supervisory authority — in particular, in the Member State of your habitual residence, your place of work, or the place of the alleged infringement.

Useful starting points:

• European Data Protection Board — overview of all national authorities: https://edpb.europa.eu/about-edpb/about-edpb/members_en
• Ireland (lead authority for many cross-border cases): Data Protection Commission, https://www.dataprotection.ie
• United Kingdom: Information Commissioner's Office (ICO), https://ico.org.uk
• Germany (Federal): BfDI, https://www.bfdi.bund.de
• France: CNIL, https://www.cnil.fr
• Netherlands: Autoriteit Persoonsgegevens, https://autoriteitpersoonsgegevens.nl
• Switzerland: FDPIC, https://www.edoeb.admin.ch

We would, however, appreciate the chance to address your concern first via privacy@illuxus.com or dpo@illuxus.com.`,
  },
  {
    title: "20. Updates to this Notice",
    body: `We may update this GDPR Notice from time to time. Material changes are notified at least 14 days in advance by email and in-product banner. The "Last updated" date at the top of this page always reflects the most recent version.

Previous versions are available on request at dpo@illuxus.com.`,
  },
  {
    title: "21. Contact",
    body: `Data Protection Officer / Privacy Lead — dpo@illuxus.com
General privacy enquiries — privacy@illuxus.com
Grievance Officer — grievance@illuxus.com
Post — Privacy Office, Illuxus Technologies Private Limited, 4th Floor, Lighthouse Tower, Bandra Kurla Complex, Mumbai – 400 051, Maharashtra, India.
Phone — +91 22 6000 0001

We aim to respond to all GDPR enquiries within 30 days. Most requests are resolved within 5 business days.`,
  },
];

export default function GdprPage() {
  return (
    <div className="min-h-screen bg-background">
      <SiteHeader />

      <section className="pt-24 pb-10 text-center px-4">
        <p className="text-sm font-medium text-primary mb-3 uppercase tracking-widest">Legal</p>
        <h1 className="text-3xl sm:text-4xl font-bold tracking-tight mb-3">GDPR Notice</h1>
        <p className="text-muted-foreground text-[14px]">
          For EU / EEA, UK and Swiss residents · Last updated: 20 June 2026 · Version 1.0
        </p>
      </section>

      <section className="max-w-3xl mx-auto px-4 sm:px-6 pb-24 space-y-10">
        <div className="text-[14px] text-muted-foreground leading-relaxed border border-border bg-card rounded-xl p-5 space-y-3">
          <p>
            This GDPR Notice supplements our{" "}
            <a href="/privacy" className="text-primary hover:underline">Privacy Policy</a> for
            individuals protected by the EU GDPR, the UK GDPR, the Swiss FADP, or comparable
            international data-protection regimes. It explains your rights and how to exercise them.
          </p>
          <p>
            Read together with the{" "}
            <a href="/cookies" className="text-primary hover:underline">Cookie Policy</a> and the{" "}
            <a href="/terms" className="text-primary hover:underline">Terms of Service</a>.
          </p>
        </div>

        {sections.map((s) => (
          <div key={s.title}>
            <h2 className="text-lg font-semibold mb-3">{s.title}</h2>
            <p className="text-[14px] text-muted-foreground leading-relaxed whitespace-pre-line">{s.body}</p>
          </div>
        ))}
      </section>

    </div>
  );
}
