/**
 * Template presets for the brochure editor. Each preset takes event-
 * provided values (title, date, venue, cover image URL, organizer
 * branding, abstract text, learning outcomes, etc.) and returns a
 * fully-populated `Brochure_Document` — every text block, image, and
 * shape is a separate editable element the organizer can select and
 * modify.
 *
 * The Poster_Bold pages (cover, abstract, why-sponsor, agenda, pricing,
 * partnership packages) follow the DevOps Connect reference brochure:
 * an off-white cover with a huge stacked title, full-bleed accent and
 * black content pages, and the event lockup (logo + stacked title) at
 * the top of every inner page. Card heights, wraps and headline sizes
 * come from `editor-text-metrics.ts` rather than fixed guesses, so the
 * layout holds for copy of any length.
 *
 * The Classic pages (table agenda, speakers, sponsors, venue) keep
 * their plain heading-and-underline look.
 */
import {
  A4_HEIGHT_MM,
  A4_WIDTH_MM,
  generateId,
  newDocument,
  newImageElement,
  newPage,
  newPillElement,
  newShapeElement,
  newTextElement,
  type BrochureDocument,
  type BrochureElement,
  type BrochurePage,
} from "./editor-document";
import {
  balanceLines,
  estimateTextHeightMm,
  estimateTextWidthMm,
  fitFontSizePt,
  wrapTextLines,
} from "./editor-text-metrics";
import { ptToMm } from "./editor-units";
import type { BrochureSectionId, BrochureTheme } from "../brochure-templates";
import {
  buildAgendaSectionContent,
  buildSpeakerRows,
  buildSponsorshipPackagesContent,
  buildVenueLogisticsContent,
  groupSponsorsByTierOrdered,
  type AgendaRow,
  type AgendaSessionInput,
  type SpeakerInput,
  type SponsorInput,
  type SponsorshipCell,
  type SponsorshipPackagesInput,
  type VenueLogisticsInput,
} from "../brochure-sections";

/**
 * Bump this integer whenever `seedBrochureDocument`'s visual output
 * changes in a way that should invalidate a previously-saved editor
 * document (layout numbers, heading sizes, field order/labels, table
 * styling, etc — anything that makes an OLD saved document look
 * different from what a FRESH seed now produces for the same input).
 *
 * This is the fix for a real structural bug: `BrochureEditorDialog`
 * always prefers a saved `Brochure_Document` (from Supabase) over a
 * fresh seed, with no way to tell whether that saved snapshot was
 * generated by an OLDER version of this file. Every time this seed's
 * layout was corrected to better match the live jsPDF preview, any
 * organizer who had already opened (and especially saved from) the
 * editor kept seeing the stale, pre-fix layout indefinitely — the
 * live preview always regenerates from current code, but the saved
 * editor document does not, so the two silently diverged forever with
 * no way for the organizer to know why or fix it themselves.
 *
 * `BrochureEditorDialog` compares this constant against the version
 * stamped on a saved document (`brochurePrefs.editorDocument.
 * templateVersion` in `page-form/types.ts`) and automatically falls
 * back to a fresh seed when the saved version is missing or older —
 * see the `isStaleSavedDocument` check there. A saved document from
 * before this constant existed has no `templateVersion` field at all,
 * which is treated as "older than any real version" (i.e. always
 * stale), since every pre-versioning seed output is exactly the kind
 * of drift this mechanism exists to catch.
 */
/**
 * Version history:
 *   1 — Initial versioned seed.
 *   2 — Poster_Bold layout aligned to the DevOps Connect reference:
 *       - Cover: top logo + huge title + subtitle + two outlined
 *         date/venue pill-chips + hero image + orange "shoulder"
 *         bleeds + white rounded footer band with producer credit +
 *         social icons.
 *       - Agenda ("timetable-cards" layout): two-column chronological
 *         split, per-row colored bar (black for keynote/panel/fireside/
 *         workshop, accent for everything else), full-width title bar,
 *         description body directly below the row on white with dark
 *         text. Big centered "Event Agenda" heading + top logo.
 *   3 — Cards are pre-grouped. Every multi-primitive card the seed builds —
 *       speaker tile, pricing card, agenda row, sponsor card, abstract block,
 *       outcome chip, numbered row — tags its parts with a shared
 *       `Geometry.groupId`, so clicking one selects the whole card and
 *       resizing the card resizes all of it. Before this, clicking a speaker
 *       tile selected only the background rectangle, so a resize grew the
 *       backing box and left the photo and text at their original size.
 *
 *       This is why the bump matters for already-saved documents: they have no
 *       group tags, so their cards stay loose. The notice on open points at
 *       "Reset to template" for organizers who want the grouped layout; the
 *       alternative is to marquee-select a card and press Ctrl+G, which
 *       produces the same result without discarding their edits.
 *   4 — Poster_Bold rebuilt against the reference PDFs. Text is measured
 *       instead of guessed, so cards fit their copy and nothing is clipped
 *       or runs off the page; the cover title is sized to its space; every
 *       inner page carries the event lockup; the agenda shows start times,
 *       three bar styles and bulleted descriptions, balances its two columns
 *       and continues onto further pages; pricing cards, the registration
 *       form, the why-sponsor table and the partnership packages table all
 *       follow the reference. Speakers and partnership packages paginate.
 */
export const EDITOR_SEED_VERSION = 4;

/** Input for template pre-loading. Everything the seed needs to lay out a
 *  brochure, already resolved by the caller (colors, font, date text).
 */
export interface TemplateSeedInput {
  eventTitle: string;
  /** Human-readable date range, e.g. "12 Aug 2026 | 09:00 AM onwards". */
  dateText: string;
  /** Human-readable venue name / city. */
  venueText: string;
  /** Cover hero image URL. Empty string is allowed; the cover then shows
   *  only the accent band where the image would sit. */
  coverImageUrl: string;
  /** Event logo / icon. Sits above the title on the cover and beside the
   *  event name at the top of every inner page. */
  logoUrl?: string;
  /** Variant of the logo for the accent-colored and black pages, where a
   *  logo in the accent color would disappear. Falls back to `logoUrl`. */
  logoOnDarkUrl?: string;
  /** Producer/organizer logo shown at the cover bottom-left. */
  organizerLogoUrl?: string;
  /** Subtitle under the cover title (e.g. "Redefining DevOps in the Era
   *  of Intelligent Automation"). */
  coverTagline?: string;
  /** Optional short chip labels (e.g. ["Autonomy", "Governance", "Capital"]). */
  coverPills?: string[];
  /** Optional cover-footer social icons — same shape as
   *  `posterContent.socialLinks`. Rendered as a right-aligned row of brand
   *  icons on the cover's footer band. */
  socialLinks?: Array<{
    platform: "linkedin" | "instagram" | "facebook" | "twitter";
    url?: string;
  }>;
  /** Optional abstract body copy for the abstract page. */
  abstract?: string;
  /** Optional featured body copy for the abstract page. */
  featured?: string;
  /** Optional learning-outcomes chips (up to 6). */
  learningOutcomes?: string[];
  /** Optional numbered value-prop items for the "Why Sponsor?" or
   *  "Focus of the Summit" page. */
  numberedItems?: string[];
  /** Pricing cards for the Poster_Bold Pricing page. */
  pricingCards?: Array<{ title: string; subtitle?: string | null; price: string; discounts?: string[] | null }>;
  /** Whether to render the blank registration-form grid below the
   *  pricing cards. */
  showRegistrationForm?: boolean;
  /** Resolved accent color (theme default with any organizer override
   *  already applied) — callers MUST pass `resolveBrochureTheme(...)`'s
   *  `accentColor`, not a raw theme default, so an organizer's color
   *  override is reflected in the editor exactly like the live preview. */
  accentColor?: string;
  /** Primary text color for cover title (contrasting the background). */
  titleColor?: string;
  /** Resolved font family (theme default with any organizer override
   *  already applied) — same precedence note as `accentColor`. */
  fontFamily?: string;

  // ── Event data pages ────────────────────────────────────────────
  //
  // When any of these is absent or empty, the corresponding page is
  // skipped entirely (the organizer can still add it manually via the
  // "add page" control in the pages bar).
  sessions?: AgendaSessionInput[];
  speakers?: SpeakerInput[];
  sponsors?: SponsorInput[];
  venueLogistics?: VenueLogisticsInput;
  /** Benefits × tiers sponsorship comparison table. Omitted
   *  (undefined/null benefits or tiers) means the page is skipped. */
  sponsorshipPackages?: SponsorshipPackagesInput;
}

// ─── Unified section-driven seed ────────────────────────────────────────────
//
// `seedBrochureDocument` is the ONE seed entry point. It walks the resolved
// section id list (`resolveSectionLayout(sectionLayout)` in the caller),
// building the editable page — or pages, for sections that paginate — for
// each one. A section that yields no content is skipped. Unsupported section
// ids (`whoShouldAttend`, `solutionProviders`, `highlights` — Corporate_Bold-
// only pages with no editor page builder yet) are skipped rather than
// throwing, so a legacy Corporate_Bold config still opens with whatever
// subset of its pages the editor can represent.
export function seedBrochureDocument(
  input: TemplateSeedInput,
  theme: BrochureTheme,
  resolvedSectionIds: BrochureSectionId[]
): BrochureDocument {
  const accent = input.accentColor ?? theme.defaultColors.accentColor;
  const fontFamily = input.fontFamily ?? theme.defaultColors.fontFamily ?? "Poppins";
  const isCorporateBold = theme.id === "corporate-bold";
  const coverTitleColor = input.titleColor ?? (isCorporateBold ? "#ffffff" : INK);
  const ctx: SeedContext = { input, theme, accent, fontFamily };

  const doc = newDocument(input.eventTitle || "Untitled Brochure");
  const pages: BrochurePage[] = [];

  for (const id of resolvedSectionIds) {
    pages.push(...buildEditorPagesForSection(id, ctx, coverTitleColor, isCorporateBold));
  }

  return {
    ...doc,
    pages: pages.length > 0 ? pages : [newPage()],
    templateVersion: EDITOR_SEED_VERSION,
  };
}

/** Everything a page builder needs, resolved once per seed. */
interface SeedContext {
  input: TemplateSeedInput;
  theme: BrochureTheme;
  accent: string;
  fontFamily: string;
}

function buildEditorPagesForSection(
  id: BrochureSectionId,
  ctx: SeedContext,
  coverTitleColor: string,
  isCorporateBold: boolean
): BrochurePage[] {
  const { input, theme } = ctx;
  const one = (page: BrochurePage | null): BrochurePage[] => (page ? [page] : []);
  switch (id) {
    case "cover":
      return one(
        isCorporateBold ? buildCorporateBoldCoverPage(ctx, coverTitleColor) : buildPosterBoldCoverPage(ctx, coverTitleColor)
      );
    case "agenda":
      return theme.agenda.layout === "timetable-cards"
        ? buildAgendaTimetablePages(ctx)
        : buildAgendaTablePages(ctx);
    case "speakers":
      return buildSpeakersPages(ctx);
    case "sponsors":
      return one(buildSponsorsPage(ctx));
    case "venueLogistics":
      return one(buildVenuePage(ctx));
    case "abstract":
      return buildAbstractPages(ctx);
    case "whySponsor":
      return one(buildNumberedListPage(ctx, input.numberedItems ?? [], "Why Sponsor?"));
    case "pricing":
      return one(buildPricingPage(ctx));
    case "focusOfSummit":
      return one(buildNumberedListPage(ctx, input.numberedItems ?? [], "Focus of the Summit"));
    case "sponsorshipPackages":
      return buildSponsorshipPackagesPages(ctx);
    // Corporate_Bold-only sections with no editor page builder yet.
    case "whoShouldAttend":
    case "solutionProviders":
    case "highlights":
      return [];
    default:
      return [];
  }
}

// ─── Shared page plumbing ──────────────────────────────────────────────────

const PAGE_W = A4_WIDTH_MM;
const PAGE_H = A4_HEIGHT_MM;
/** Off-white page stock used by the Poster_Bold light pages and cards. */
const PAPER = "#f6f6f6";
const INK = "#000000";
/** Thin accent strip along the bottom edge of the non-accent poster pages. */
const BOTTOM_BAR_H = 2;
/** Lowest y content may reach on a page that carries the bottom bar. */
const CONTENT_BOTTOM = PAGE_H - BOTTOM_BAR_H - 6;
/**
 * Share of a text box's width the seed plans to fill. The estimate uses
 * exact Poppins metrics, so this only has to absorb rounding — but it must
 * stay below 1: planning one line too few makes the next block overlap,
 * while one too many only leaves a small gap.
 */
const WRAP_FIT = 0.99;
/** Height of the lockup block at the top of an inner page. */
const LOCKUP_H = 18;
const LOCKUP_TOP = 24;

type Push = (el: BrochureElement) => void;

/** A page's element list plus the `push` that keeps z-order = paint order. */
function createPusher(): { elements: BrochureElement[]; push: Push } {
  const elements: BrochureElement[] = [];
  return {
    elements,
    push: (el) => {
      el.zIndex = elements.length;
      elements.push(el);
    },
  };
}

function makePage(kind: string, background: string, elements: BrochureElement[]): BrochurePage {
  return {
    id: `page-${kind}-${Math.random().toString(36).slice(2, 8)}`,
    width: PAGE_W,
    height: PAGE_H,
    background: { type: "solid", color: background },
    elements,
  };
}

function isPosterTheme(theme: BrochureTheme): boolean {
  return theme.id === "poster-bold";
}

/**
 * Wraps a page's `push` helper so everything pushed through the result is tagged
 * as ONE card (see `Geometry.groupId`).
 *
 * The templates express a card as several loose primitives — a background rect,
 * a photo, a name, a job title. Without a shared tag, clicking a speaker tile
 * in the editor selected only the primitive under the cursor, so "resize the
 * card" resized the backing rectangle and left the photo and text behind. Tagging
 * at seed time is what makes a template's cards behave like objects on first
 * open, rather than requiring the organizer to marquee-select and group them by
 * hand.
 *
 * Call once per card, inside the loop:
 *
 *   for (const row of rows) {
 *     const pushCard = cardPusher(push);
 *     pushCard(newShapeElement({ ... }));   // background
 *     pushCard(newImageElement({ ... }));   // photo
 *   }
 *
 * Neither renderer reads `groupId`; both keep drawing a flat element list.
 */
function cardPusher(push: Push): Push {
  const groupId = generateId("group");
  return (el: BrochureElement) => {
    el.groupId = groupId;
    push(el);
  };
}

function rect(
  x: number,
  y: number,
  width: number,
  height: number,
  fill: string,
  cornerRadius = 0,
  stroke = "transparent",
  strokeWidth = 0
): BrochureElement {
  return newShapeElement({ x, y, width, height, shape: "rect", fill, stroke, strokeWidth, cornerRadius });
}

function bottomBar(accent: string): BrochureElement {
  return rect(0, PAGE_H - BOTTOM_BAR_H, PAGE_W, BOTTOM_BAR_H, accent);
}

// ─── Inline icons ──────────────────────────────────────────────────────────
//
// The document model has no icon element, and the canvas has no icon font.
// Small SVGs carried as `data:` URLs in ordinary image elements give real
// glyphs (brand marks, the pricing arrow, check / cross marks) that render
// identically on the canvas and in the export, stay crisp at 300 DPI, and
// can still be swapped or deleted like any other image.

function svgIcon(body: string): string {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="192" height="192" viewBox="0 0 48 48">${body}</svg>`;
  return `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`;
}

const STROKE = `fill="none" stroke-linecap="round" stroke-linejoin="round"`;

function arrowIcon(accent: string): string {
  return svgIcon(
    `<circle cx="24" cy="24" r="24" fill="${accent}"/><path d="M13 24h21M26 15l9 9-9 9" ${STROKE} stroke="#fff" stroke-width="3.2"/>`
  );
}

const CHECK_BULLET_ICON = svgIcon(
  `<circle cx="24" cy="24" r="24" fill="#000"/><path d="M13.5 24.5l7.2 7.2L34.5 17" ${STROKE} stroke="#fff" stroke-width="4.6"/>`
);
const CROSS_ICON = svgIcon(`<path d="M9 9l30 30M39 9L9 39" ${STROKE} stroke="#e5202e" stroke-width="5.5"/>`);
const TICK_ICON = svgIcon(`<path d="M7 26l11 11L41 12" ${STROKE} stroke="#16a34a" stroke-width="5.5"/>`);

const SOCIAL_ICONS: Record<string, string> = {
  linkedin: svgIcon(
    `<circle cx="24" cy="24" r="24" fill="#0a66c2"/><g fill="#fff"><circle cx="16.4" cy="15.6" r="2.7"/><rect x="14.1" y="20.6" width="4.6" height="13.4"/><path d="M22 20.6h4.4v1.9c.8-1.4 2.5-2.3 4.5-2.3 3.9 0 5.1 2.4 5.1 6.1V34h-4.6v-6.8c0-1.7-.5-2.8-2.1-2.8-1.7 0-2.7 1.2-2.7 3V34H22z"/></g>`
  ),
  instagram: svgIcon(
    `<defs><linearGradient id="ig" x1="0" y1="1" x2="1" y2="0"><stop offset="0" stop-color="#feda75"/><stop offset=".3" stop-color="#fa7e1e"/><stop offset=".55" stop-color="#d62976"/><stop offset=".8" stop-color="#962fbf"/><stop offset="1" stop-color="#4f5bd5"/></linearGradient></defs><circle cx="24" cy="24" r="24" fill="url(#ig)"/><g fill="none" stroke="#fff" stroke-width="2.6"><rect x="13.3" y="13.3" width="21.4" height="21.4" rx="6.2"/><circle cx="24" cy="24" r="5.1"/></g><circle cx="30.3" cy="17.7" r="1.5" fill="#fff"/>`
  ),
  facebook: svgIcon(
    `<circle cx="24" cy="24" r="24" fill="#1877f2"/><path fill="#fff" d="M26.4 39V26h4.3l.7-5.1h-5v-3.2c0-1.5.4-2.5 2.5-2.5h2.7v-4.5c-.5-.1-2-.2-3.9-.2-3.8 0-6.4 2.3-6.4 6.6v3.8H17V26h4.3v13z"/>`
  ),
  twitter: svgIcon(
    `<circle cx="24" cy="24" r="24" fill="#1da1f2"/><path fill="#fff" transform="translate(11 11.6) scale(1.08)" d="M23.953 4.57a10 10 0 01-2.825.775 4.958 4.958 0 002.163-2.723c-.951.555-2.005.959-3.127 1.184a4.92 4.92 0 00-8.384 4.482C7.69 8.095 4.067 6.13 1.64 3.162a4.822 4.822 0 00-.666 2.475c0 1.71.87 3.213 2.188 4.096a4.904 4.904 0 01-2.228-.616v.06a4.923 4.923 0 003.946 4.827 4.996 4.996 0 01-2.212.085 4.936 4.936 0 004.604 3.417 9.867 9.867 0 01-6.102 2.105c-.39 0-.779-.023-1.17-.067a13.995 13.995 0 007.557 2.209c9.053 0 13.998-7.496 13.998-13.985 0-.21 0-.42-.015-.63A9.935 9.935 0 0024 4.59z"/>`
  ),
};

// ─── Event lockup (top of every inner Poster_Bold page) ────────────────────

/**
 * Pushes the event lockup — the logo with the event name stacked beside it —
 * centered at the top of an inner page, as on every page of the reference
 * brochure. The name's first line is set larger than its second
 * ("DevOps" over "Connect"); with no logo configured the name stands alone,
 * so a page is never left without its masthead. Returns the lockup's
 * bottom edge.
 *
 * `surface` picks the logo variant: accent-colored and black pages use
 * `logoOnDarkUrl` when one is set.
 */
function pushLockup(push: Push, ctx: SeedContext, textColor: string, surface: "paper" | "color"): number {
  const { input, fontFamily } = ctx;
  const logoSrc = (surface === "color" ? input.logoOnDarkUrl : undefined) || input.logoUrl || "";
  const lines = balanceLines(input.eventTitle.trim(), 2);
  if (!logoSrc && lines.length === 0) return LOCKUP_TOP;

  let primaryPt = lines.length > 1 ? 30 : 26;
  let secondaryPt = 19;
  const widthAt = (p: number, s: number): number =>
    Math.max(
      lines[0] ? estimateTextWidthMm(lines[0], p, true) : 0,
      lines[1] ? estimateTextWidthMm(lines[1], s, true) : 0
    );
  const maxTextW = 118;
  const shrink = Math.min(1, maxTextW / Math.max(1, widthAt(primaryPt, secondaryPt)));
  primaryPt *= shrink;
  secondaryPt *= shrink;
  const textW = lines.length > 0 ? widthAt(primaryPt, secondaryPt) + 2 : 0;

  const logoW = logoSrc ? 30 : 0;
  const gap = logoSrc && lines.length > 0 ? 4 : 0;
  let x = (PAGE_W - (logoW + gap + textW)) / 2;
  const pushPart = cardPusher(push);

  if (logoSrc) {
    pushPart(
      newImageElement({
        x,
        y: LOCKUP_TOP,
        width: logoW,
        height: LOCKUP_H,
        src: logoSrc,
        fit: "contain",
        // Flush against the name rather than floating in the middle of its box.
        focalX: lines.length > 0 ? 1 : 0.5,
      })
    );
    x += logoW + gap;
  }

  const primaryH = ptToMm(primaryPt);
  const secondaryH = lines[1] ? ptToMm(secondaryPt) : 0;
  let textY = LOCKUP_TOP + (LOCKUP_H - primaryH - secondaryH) / 2;
  if (lines[0]) {
    pushPart(
      newTextElement({
        x,
        y: textY,
        width: textW,
        height: primaryH + 1,
        content: lines[0],
        fontFamily,
        fontSize: primaryPt,
        fontWeight: "bold",
        color: textColor,
        align: "left",
        lineHeight: 1,
      })
    );
    textY += primaryH;
  }
  if (lines[1]) {
    pushPart(
      newTextElement({
        x,
        y: textY,
        width: textW,
        height: secondaryH + 1,
        content: lines[1],
        fontFamily,
        fontSize: secondaryPt,
        fontWeight: "bold",
        color: textColor,
        align: "left",
        lineHeight: 1,
      })
    );
  }
  return LOCKUP_TOP + LOCKUP_H;
}

/**
 * Largest headline that fits `maxWidthMm` × `maxHeightMm`, trying one to
 * three balanced lines and keeping whichever allows the biggest type (fewer
 * lines win a tie). This is what lets a two-word title fill the cover the way
 * the reference does while a six-word one still fits.
 */
function fitHeadline(
  title: string,
  maxWidthMm: number,
  maxHeightMm: number,
  maxPt: number,
  minPt: number,
  lineHeight: number
): { lines: string[]; fontSize: number } {
  let best: { lines: string[]; fontSize: number } | null = null;
  for (let n = 1; n <= 3; n += 1) {
    const lines = balanceLines(title, n);
    if (lines.length < n) break;
    const byWidth = fitFontSizePt(lines, maxWidthMm, maxPt, minPt, true);
    const byHeight = maxHeightMm / (n * ptToMm(1) * lineHeight);
    const fontSize = Math.max(minPt, Math.min(byWidth, byHeight));
    if (!best || fontSize > best.fontSize + 0.5) best = { lines, fontSize };
  }
  return best ?? { lines: [title], fontSize: minPt };
}

// ─── Cover page builders ───────────────────────────────────────────────────

/**
 * The cover, after the reference brochure: logo, a huge stacked title, the
 * subtitle, outlined date and venue pills, then the hero image standing on
 * an accent block, with a white rounded footer card carrying the organizer
 * credit and social icons, and a thin accent strip along the bottom edge.
 *
 * Every piece is its own editable element. Nothing below the title has a
 * fixed position — each block is placed under the one before it, so a long
 * title or a missing subtitle just moves the rest.
 */
function buildPosterBoldCoverPage(ctx: SeedContext, titleColor: string): BrochurePage {
  const { input, accent, fontFamily, theme } = ctx;
  const { elements, push } = createPusher();
  const paper = isPosterTheme(theme) ? PAPER : "#ffffff";
  const centerX = PAGE_W / 2;

  // ── 1. Logo ───────────────────────────────────────────────────────
  let cursorY = 18;
  if (input.logoUrl) {
    const logoW = 44;
    const logoH = 19;
    push(newImageElement({ x: centerX - logoW / 2, y: cursorY, width: logoW, height: logoH, src: input.logoUrl, fit: "contain" }));
    cursorY += logoH + 5;
  } else {
    cursorY += 12;
  }

  // ── 2. Title ──────────────────────────────────────────────────────
  const titleLineHeight = 1;
  const { lines: titleLines, fontSize: titleSize } = fitHeadline(
    input.eventTitle.trim() || "Untitled Event",
    172,
    54,
    74,
    20,
    titleLineHeight
  );
  const titleH = titleLines.length * ptToMm(titleSize) * titleLineHeight;
  push(
    newTextElement({
      // Wider than the fit width: the line breaks are explicit, and the slack
      // keeps a font that runs wider than the estimate from re-wrapping.
      x: 5,
      y: cursorY,
      width: PAGE_W - 10,
      height: titleH + 4,
      content: titleLines.join("\n"),
      fontFamily,
      fontSize: titleSize,
      fontWeight: "bold",
      color: titleColor,
      align: "center",
      lineHeight: titleLineHeight,
    })
  );
  cursorY += titleH + 5;

  // ── 3. Subtitle ───────────────────────────────────────────────────
  const subtitle = input.coverTagline?.trim();
  if (subtitle) {
    const subW = 128;
    const subPt = 18;
    const subLH = 1.25;
    const subH = estimateTextHeightMm(subtitle, subW * WRAP_FIT, subPt, subLH);
    push(
      newTextElement({
        x: centerX - subW / 2,
        y: cursorY,
        width: subW,
        height: subH + 3,
        content: subtitle,
        fontFamily,
        fontSize: subPt,
        fontWeight: "normal",
        color: titleColor,
        align: "center",
        lineHeight: subLH,
      })
    );
    cursorY += subH + 5;
  }

  // ── 4. Date + venue pills ─────────────────────────────────────────
  const chips = [input.dateText, input.venueText].map((c) => c?.trim()).filter((c): c is string => !!c);
  if (chips.length > 0) {
    const chipH = 13.5;
    const chipGap = 3;
    const chipPadX = 7;
    const maxRowW = PAGE_W - 24;
    let chipPt = 15;
    const rowWidth = (pt: number): number =>
      chips.reduce((sum, c) => sum + estimateTextWidthMm(c, pt) + chipPadX * 2, 0) + chipGap * (chips.length - 1);
    while (chipPt > 8 && rowWidth(chipPt) > maxRowW) chipPt -= 0.5;
    let chipX = centerX - rowWidth(chipPt) / 2;
    for (const chip of chips) {
      const chipW = estimateTextWidthMm(chip, chipPt) + chipPadX * 2;
      push(
        newPillElement({
          x: chipX,
          y: cursorY,
          width: chipW,
          height: chipH,
          text: chip,
          fontFamily,
          fontSize: chipPt,
          textColor: titleColor,
          fillColor: paper,
          strokeColor: titleColor,
          strokeWidth: 0.55,
        })
      );
      chipX += chipW + chipGap;
    }
    cursorY += chipH + 4;
  }

  // ── 5. Accent block + hero image ──────────────────────────────────
  //
  // One rounded accent block sits behind the image's lower edge. A cut-out
  // hero (the reference's skyline) lets it show either side as two orange
  // shoulders; a full-width photo simply covers it. Both the block and the
  // image run on underneath the footer card, which hides their lower edges.
  const footerTop = 236;
  const blockTop = footerTop - 19;
  const hasHero = !!input.coverImageUrl?.trim();
  if (!hasHero) {
    // Nothing to stand on the block: sit the title group in the middle of
    // the open space rather than leaving it stranded at the top of the page.
    const shift = Math.max(0, (blockTop - 16 - cursorY) / 2);
    for (const el of elements) el.y += shift;
  }
  push(rect(5, blockTop, PAGE_W - 10, 40, accent, 10));
  if (hasHero) {
    const heroTop = Math.min(cursorY, footerTop - 40);
    push(
      newImageElement({
        x: 0,
        y: heroTop,
        width: PAGE_W,
        height: footerTop + 6 - heroTop,
        src: input.coverImageUrl,
        fit: "cover",
        focalY: 0.35,
      })
    );
  }

  // ── 6. Footer card + bottom strip ─────────────────────────────────
  push(rect(-0.4, footerTop, PAGE_W + 0.8, PAGE_H - footerTop + 20, "#ffffff", 12, accent, 0.4));
  push(bottomBar(accent));

  // ── 7. Footer content ─────────────────────────────────────────────
  const marginX = 21;
  if (input.organizerLogoUrl) {
    push(
      newTextElement({
        x: marginX,
        y: footerTop + 19,
        width: 90,
        height: 5,
        content: "Conceptualized & Organized by",
        fontFamily,
        fontSize: 9,
        fontWeight: "bold",
        color: INK,
        align: "left",
        lineHeight: 1,
      })
    );
    push(
      newImageElement({
        x: marginX,
        y: footerTop + 26,
        width: 58,
        height: 18,
        src: input.organizerLogoUrl,
        fit: "contain",
        focalX: 0,
      })
    );
  }

  const socials = (input.socialLinks ?? []).filter((s) => SOCIAL_ICONS[s.platform]);
  if (socials.length > 0) {
    const iconSize = 8;
    const iconGap = 2;
    const rowW = socials.length * iconSize + (socials.length - 1) * iconGap;
    const rowRight = PAGE_W - marginX;
    const captionW = 50;
    const rowCenter = rowRight - Math.max(rowW, 36) / 2;
    push(
      newTextElement({
        x: rowCenter - captionW / 2,
        y: footerTop + 29,
        width: captionW,
        height: 4,
        content: "Follow us on social media",
        fontFamily,
        fontSize: 7.5,
        fontWeight: "bold",
        color: INK,
        align: "center",
        lineHeight: 1,
      })
    );
    let iconX = rowCenter - rowW / 2;
    for (const s of socials) {
      push(newImageElement({ x: iconX, y: footerTop + 35, width: iconSize, height: iconSize, src: SOCIAL_ICONS[s.platform], fit: "contain" }));
      iconX += iconSize + iconGap;
    }
  }

  return makePage("cover", paper, elements);
}

function buildCorporateBoldCoverPage(ctx: SeedContext, titleColor: string): BrochurePage {
  // Reuse the Poster Bold cover geometry but with a gradient bg + white text.
  const page = buildPosterBoldCoverPage(ctx, titleColor);
  page.background = { type: "gradient", top: "#1a0730", bottom: "#3a1152" };
  return page;
}

// ─── Abstract page ─────────────────────────────────────────────────────────

/**
 * Abstract page: accent background, lockup, then the "ABSTRACT" and
 * "Featured" cards (a black label tab overlapping the top edge of an
 * off-white card) and the two-column grid of black learning-outcome tiles.
 *
 * Each card is as tall as its copy. If the whole page would run past the
 * bottom edge the body size steps down until it fits; copy too long even at
 * the smallest readable size carries the remaining blocks onto another page
 * rather than spilling off this one. Returns no pages when all three are
 * empty.
 */
function buildAbstractPages(ctx: SeedContext): BrochurePage[] {
  const { input, accent, fontFamily } = ctx;
  const abstractText = input.abstract?.trim();
  const featuredText = input.featured?.trim();
  const outcomes = (input.learningOutcomes ?? []).map((s) => s?.trim()).filter((s): s is string => !!s).slice(0, 6);
  if (!abstractText && !featuredText && outcomes.length === 0) return [];

  const pages: BrochurePage[] = [];
  let { elements, push } = createPusher();
  const lockupBottom = pushLockup(push, ctx, INK, "color");
  const nextPage = (): void => {
    pages.push(makePage("abstract", accent, elements));
    ({ elements, push } = createPusher());
    pushLockup(push, ctx, INK, "color");
  };

  const cardX = 12;
  const cardW = PAGE_W - cardX * 2;
  const cardPadX = 8.5;
  const bodyW = cardW - cardPadX * 2;
  const bodyLH = 1.2;
  const labelW = 56;
  const labelH = 13;
  const cardPadTop = labelH / 2 + 6.5;
  const cardPadBottom = 8;
  const cardGap = 4.5;
  const headingGap = 7;
  const blocks = [
    { label: "ABSTRACT", body: abstractText },
    { label: "Featured", body: featuredText },
  ].filter((b): b is { label: string; body: string } => !!b.body);

  const chipCols = 2;
  const chipX = 21;
  const chipGap = 3.5;
  const chipW = (PAGE_W - chipX * 2 - chipGap) / chipCols;
  const chipH = 20.5;
  const chipRows = Math.ceil(outcomes.length / chipCols);
  // Heading (10) + gap (5) + the tile grid.
  const outcomesH = outcomes.length > 0 ? 15 + chipRows * chipH + (chipRows - 1) * chipGap : 0;

  const firstLabelTop = lockupBottom + 13;
  const bodyHeight = (body: string, pt: number): number => estimateTextHeightMm(body, bodyW * WRAP_FIT, pt, bodyLH);
  const pageBottom = PAGE_H - 9;
  let bodyPt = 18;
  const neededAt = (pt: number): number =>
    blocks.reduce((sum, b) => sum + labelH / 2 + cardPadTop + bodyHeight(b.body, pt) + cardPadBottom + cardGap, 0) +
    (outcomes.length > 0 ? headingGap - cardGap + outcomesH : 0);
  while (bodyPt > 11 && firstLabelTop + neededAt(bodyPt) > pageBottom) bodyPt -= 0.5;

  let cursorY = firstLabelTop;
  for (const block of blocks) {
    const bodyH = bodyHeight(block.body, bodyPt);
    const cardH = cardPadTop + bodyH + cardPadBottom;
    if (cursorY > firstLabelTop && cursorY + labelH / 2 + cardH > pageBottom) {
      nextPage();
      cursorY = firstLabelTop;
    }
    const cardY = cursorY + labelH / 2;
    // Card, label tab and copy move and resize as one block. The card goes
    // down first so the label tab paints over its top edge.
    const pushCard = cardPusher(push);
    pushCard(rect(cardX, cardY, cardW, cardH, PAPER, 3));
    pushCard(rect(PAGE_W / 2 - labelW / 2, cursorY, labelW, labelH, INK, 3));
    pushCard(
      newTextElement({
        x: PAGE_W / 2 - labelW / 2,
        y: cursorY,
        width: labelW,
        height: labelH,
        content: block.label,
        fontFamily,
        fontSize: 14,
        fontWeight: "bold",
        color: "#ffffff",
        align: "center",
        lineHeight: 1,
        verticalAlign: "middle",
      })
    );
    pushCard(
      newTextElement({
        x: cardX + cardPadX,
        y: cardY + cardPadTop,
        width: bodyW,
        height: bodyH + cardPadBottom - 1,
        content: block.body,
        fontFamily,
        fontSize: bodyPt,
        fontWeight: "normal",
        color: INK,
        align: "center",
        lineHeight: bodyLH,
      })
    );
    cursorY = cardY + cardH + cardGap;
  }

  if (outcomes.length > 0) {
    if (cursorY > firstLabelTop) {
      cursorY += headingGap - cardGap;
      if (cursorY + outcomesH > pageBottom) {
        nextPage();
        cursorY = firstLabelTop;
      }
    }
    push(
      newTextElement({
        x: 12,
        y: cursorY,
        width: PAGE_W - 24,
        height: 10,
        content: "LEARNING OUTCOMES",
        fontFamily,
        fontSize: 22,
        fontWeight: "bold",
        color: INK,
        align: "center",
        lineHeight: 1,
      })
    );
    const gridTop = cursorY + 15;
    // Two lines is all a tile holds; a longer outcome steps its type down.
    const chipPt = (label: string): number => {
      let pt = 15.5;
      while (pt > 10 && wrapTextLines(label, (chipW - 14) * WRAP_FIT, pt, true).length > 2) pt -= 0.5;
      return pt;
    };
    for (let i = 0; i < outcomes.length; i += 1) {
      const x = chipX + (i % chipCols) * (chipW + chipGap);
      const y = gridTop + Math.floor(i / chipCols) * (chipH + chipGap);
      // Tile = black panel + its label, grouped so dragging one moves both.
      const pushChip = cardPusher(push);
      pushChip(rect(x, y, chipW, chipH, INK, 3));
      pushChip(
        newTextElement({
          x: x + 7,
          y,
          width: chipW - 14,
          height: chipH,
          content: outcomes[i],
          fontFamily,
          fontSize: chipPt(outcomes[i]),
          fontWeight: "bold",
          color: "#ffffff",
          align: "center",
          lineHeight: 1.2,
          verticalAlign: "middle",
        })
      );
    }
  }

  pages.push(makePage("abstract", accent, elements));
  return pages;
}

// ─── Numbered list page (Why Sponsor / Focus of Summit) ────────────────────

/**
 * "WHY SPONSOR?" page: black background, white lockup, a huge white title,
 * then a bordered table — an accent number column and a white cell of black
 * copy per row, hairline accent rules between rows. Each row is as tall as
 * its copy; if the table would pass the bottom edge the copy size steps
 * down until it fits. Returns `null` when there are no non-empty items.
 */
function buildNumberedListPage(ctx: SeedContext, items: string[], title: string): BrochurePage | null {
  const { accent, fontFamily } = ctx;
  const clean = items.map((s) => s?.trim()).filter((s): s is string => !!s);
  if (clean.length === 0) return null;

  const { elements, push } = createPusher();
  const lockupBottom = pushLockup(push, ctx, "#ffffff", "color");

  const heading = title.toUpperCase();
  const headingPt = fitFontSizePt([heading], 178, 58, 24, true);
  const headingH = ptToMm(headingPt);
  const headingY = lockupBottom + 10;
  push(
    newTextElement({
      x: 5,
      y: headingY,
      width: PAGE_W - 10,
      height: headingH + 2,
      content: heading,
      fontFamily,
      fontSize: headingPt,
      fontWeight: "bold",
      color: "#ffffff",
      align: "center",
      lineHeight: 1,
    })
  );

  const tableX = 15.7;
  const tableW = PAGE_W - tableX * 2;
  const numberW = 33;
  const rule = 0.35;
  const cellX = tableX + numberW;
  const cellW = tableW - numberW - rule;
  const cellPadX = 2.4;
  const copyW = cellW - cellPadX * 2;
  const copyLH = 1.4;
  const tableTop = headingY + headingH + 10;
  const tableBottomLimit = CONTENT_BOTTOM;

  const rowHeights = (pt: number): number[] =>
    clean.map((item) => Math.max(pt * 1.45, estimateTextHeightMm(item, copyW * WRAP_FIT, pt, copyLH) + pt * 0.7));
  let copyPt = 12.5;
  while (copyPt > 8 && tableTop + rowHeights(copyPt).reduce((a, b) => a + b, 0) + rule > tableBottomLimit) copyPt -= 0.5;
  const heights = rowHeights(copyPt);
  const tableH = heights.reduce((a, b) => a + b, 0) + rule;

  // One accent slab is the number column AND the rules: the white cells are
  // inset on top of it, so what shows between them is the hairline grid.
  push(rect(tableX, tableTop, tableW, tableH, accent));

  let y = tableTop;
  for (let i = 0; i < clean.length; i += 1) {
    const rowH = heights[i];
    // Row = white cell + number + copy, grouped so it drags as one.
    const pushRow = cardPusher(push);
    pushRow(rect(cellX, y + rule, cellW, rowH - rule, "#ffffff"));
    pushRow(
      newTextElement({
        x: tableX,
        y: y + rule,
        width: numberW,
        height: rowH - rule,
        content: String(i + 1),
        fontFamily,
        fontSize: Math.min(18, copyPt * 1.45),
        fontWeight: "bold",
        color: "#ffffff",
        align: "center",
        lineHeight: 1,
        verticalAlign: "middle",
      })
    );
    pushRow(
      newTextElement({
        x: cellX + cellPadX,
        y: y + rule,
        width: copyW,
        height: rowH - rule,
        content: clean[i],
        fontFamily,
        fontSize: copyPt,
        fontWeight: "normal",
        color: INK,
        align: "left",
        lineHeight: copyLH,
        verticalAlign: "middle",
      })
    );
    y += rowH;
  }

  push(bottomBar(accent));
  return makePage("list", INK, elements);
}

// ─── Pricing page ──────────────────────────────────────────────────────────

/**
 * Pricing page: accent background, white lockup, off-white pricing cards
 * (arrow badge + title, subtitle, a large price, a rule, then check-marked
 * group discounts) and, optionally, the blank registration form — three
 * attendee blocks of Name / Designation / Mobile / Email pills separated by
 * rules. Returns `null` when there are no cards and the form is off.
 */
function buildPricingPage(ctx: SeedContext): BrochurePage | null {
  const { input, accent, fontFamily } = ctx;
  const cards = (input.pricingCards ?? []).filter((c) => c && c.title?.trim() && c.price?.trim());
  const showForm = input.showRegistrationForm === true;
  if (cards.length === 0 && !showForm) return null;

  const { elements, push } = createPusher();
  const lockupBottom = pushLockup(push, ctx, "#ffffff", "color");
  let cursorY = lockupBottom + 10;

  if (cards.length > 0) {
    const gridX = 16.6;
    const gap = 3.8;
    const cardW = (PAGE_W - gridX * 2 - gap) / 2;
    const cols = Math.min(cards.length, 2);
    const padX = 7;
    const discountPitch = 6.6;
    const discountCounts = cards.map((c) => (c.discounts ?? []).filter((d) => d && d.trim()).length);
    const cardHeightFor = (count: number): number => (count > 0 ? 58 + count * discountPitch : 46);

    for (let rowStart = 0; rowStart < cards.length; rowStart += cols) {
      const rowCards = cards.slice(rowStart, rowStart + cols);
      // Cards in a row share the tallest card's height; a lone card is centered.
      const cardH = Math.max(...rowCards.map((_, i) => cardHeightFor(discountCounts[rowStart + i])));
      const rowW = rowCards.length * cardW + (rowCards.length - 1) * gap;
      const rowX = (PAGE_W - rowW) / 2;

      rowCards.forEach((card, i) => {
        const cx = rowX + i * (cardW + gap);
        const cy = cursorY;
        // Whole pricing card (panel + badge + title + price + discounts).
        const pushCard = cardPusher(push);
        pushCard(rect(cx, cy, cardW, cardH, PAPER, 3));

        const badge = 10;
        pushCard(newImageElement({ x: cx + padX, y: cy + 6.5, width: badge, height: badge, src: arrowIcon(accent), fit: "contain" }));

        const headX = cx + padX + badge + 3;
        const headW = cardW - padX - badge - 3 - 4;
        const cardTitle = card.title.trim().toUpperCase();
        const titlePt = fitFontSizePt([cardTitle], headW * WRAP_FIT, 16, 9, true);
        const subtitle = card.subtitle?.trim();
        pushCard(
          newTextElement({
            x: headX,
            y: cy + (subtitle ? 6.2 : 8.6),
            width: headW,
            height: ptToMm(titlePt) + 1,
            content: cardTitle,
            fontFamily,
            fontSize: titlePt,
            fontWeight: "bold",
            color: INK,
            align: "left",
            lineHeight: 1,
          })
        );
        if (subtitle) {
          pushCard(
            newTextElement({
              x: headX,
              y: cy + 12.6,
              width: headW,
              height: 5,
              content: subtitle,
              fontFamily,
              fontSize: 9.5,
              fontWeight: "normal",
              color: INK,
              align: "left",
              lineHeight: 1,
            })
          );
        }

        const price = card.price.trim();
        const pricePt = fitFontSizePt([price], (cardW - padX * 2) * WRAP_FIT, 36, 14, true);
        pushCard(
          newTextElement({
            x: cx + padX,
            y: cy + 24,
            width: cardW - padX * 2,
            height: 15,
            content: price,
            fontFamily,
            fontSize: pricePt,
            fontWeight: "bold",
            color: INK,
            align: "left",
            lineHeight: 1,
            verticalAlign: "middle",
          })
        );

        const discounts = (card.discounts ?? []).map((d) => d?.trim()).filter((d): d is string => !!d);
        if (discounts.length > 0) {
          pushCard(rect(cx + padX, cy + 42.6, cardW - padX * 2, 0.3, INK));
          const listX = cx + padX + 6.5;
          pushCard(
            newTextElement({
              x: listX,
              y: cy + 46.6,
              width: cardW - padX * 2 - 6.5,
              height: 5,
              content: "Group Discounts",
              fontFamily,
              fontSize: 10,
              fontWeight: "bold",
              color: INK,
              align: "left",
              lineHeight: 1,
            })
          );
          discounts.forEach((line, d) => {
            const lineY = cy + 53.4 + d * discountPitch;
            pushCard(newImageElement({ x: cx + padX, y: lineY + 0.3, width: 4, height: 4, src: CHECK_BULLET_ICON, fit: "contain" }));
            pushCard(
              newTextElement({
                x: listX,
                y: lineY,
                width: cardW - padX * 2 - 6.5,
                height: 4.6,
                content: line,
                fontFamily,
                fontSize: fitFontSizePt([line], (cardW - padX * 2 - 6.5) * WRAP_FIT, 10, 7),
                fontWeight: "normal",
                color: INK,
                align: "left",
                lineHeight: 1,
                verticalAlign: "middle",
              })
            );
          });
        }
      });
      cursorY += cardH + gap;
    }
    cursorY += 13 - gap;
  }

  if (showForm) {
    const formX = 14.8;
    const cellGap = 1;
    const cellW = (PAGE_W - formX * 2 - cellGap) / 2;
    const pillH = 9;
    const blockH = 32;
    const blockPitch = 42;
    const fields: Array<[string, string]> = [
      ["Name", "Designation"],
      ["Mobile", "Email"],
    ];
    for (let block = 0; block < 3; block += 1) {
      if (cursorY + blockH > PAGE_H - 8) break;
      if (block > 0) push(rect(formX, cursorY - 4.6, PAGE_W - formX * 2, 0.25, INK));
      // One attendee = its four labelled fields, grouped.
      const pushBlock = cardPusher(push);
      fields.forEach((pair, r) => {
        pair.forEach((label, c) => {
          const x = formX + c * (cellW + cellGap);
          const y = cursorY + r * 18;
          pushBlock(
            newTextElement({
              x,
              y,
              width: cellW,
              height: 4.4,
              content: label,
              fontFamily,
              fontSize: 9,
              fontWeight: "normal",
              color: "#ffffff",
              align: "center",
              lineHeight: 1,
            })
          );
          pushBlock(
            newPillElement({
              x,
              y: y + 5,
              width: cellW,
              height: pillH,
              text: "",
              fontFamily,
              fontSize: 9,
              textColor: INK,
              fillColor: "#ffffff",
              strokeColor: "transparent",
              strokeWidth: 0,
            })
          );
        });
      });
      cursorY += blockPitch;
    }
  }

  return makePage("pricing", accent, elements);
}

// ─── Event data pages ──────────────────────────────────────────────────────
//
// The page builders below turn the event's own data (sessions, speakers,
// sponsors, venue) into ordinary editable elements. Layout numbers are in mm.

/**
 * Shared section-heading (bold black title + short accent underline
 * beneath). Mirrors `drawHeadingUnderline` in `brochure-pdf.ts` exactly:
 *
 *   - Title text at `(theme.margins.left, theme.margins.top)`
 *   - Font size = `theme.heading.fontSizePt` (NOT a hardcoded 22pt —
 *     Classic Editorial uses 15pt, so hardcoding 22 made the editor's
 *     heading ~47% larger than the preview's, one of the visible
 *     differences reported by the organizer)
 *   - Accent underline only if `theme.heading.showAccentUnderline` is
 *     true; drawn at `y + 2` (relative to heading Y, matches the
 *     `startY + 2` offset used in `drawAgendaSection`,
 *     `drawSpeakersSection`, and `drawVenueLogisticsSection` in the
 *     preview)
 *
 * Returns the Y-cursor position where the content below the heading
 * should start, matching the preview's `y = startY + 10` / `+ 12`
 * convention so section content is vertically aligned in both
 * pipelines.
 */
function pushClassicSectionHeading(
  push: (el: BrochureElement) => void,
  theme: BrochureTheme,
  text: string,
  accent: string,
  fontFamily: string,
  /** Underline width in mm. Matches the widths hardcoded per section
   *  in `brochure-pdf.ts`: 24 for Agenda/Speakers/Sponsors, 40 for
   *  Venue & Logistics. */
  underlineWidthMm: number,
  /** Content Y-cursor offset from the heading baseline. Matches the
   *  preview's `+ 10` for Agenda/Speakers/Sponsors and `+ 12` for
   *  Venue. */
  contentOffsetMm: number
): number {
  const headingY = theme.margins.top;
  const headingX = theme.margins.left;
  push(
    newTextElement({
      x: headingX,
      y: headingY,
      width: 150,
      height: 10,
      content: text,
      fontFamily,
      fontSize: theme.heading.fontSizePt,
      fontWeight: theme.heading.fontStyle === "bold" ? "bold" : "normal",
      color: "#000000",
      align: "left",
      lineHeight: 1,
    })
  );
  if (theme.heading.showAccentUnderline) {
    push(
      newShapeElement({
        // Preview draws at `startY + 2`, but jsPDF's `doc.text` uses
        // baseline-y whereas our newTextElement uses top-left-y — the
        // heading font's baseline sits roughly at `fontSize` mm below
        // the top-left. Positioning the underline slightly below the
        // heading text (`+ 2` from the text bottom) matches the
        // preview's visual gap between text and underline.
        x: headingX,
        y: headingY + (theme.heading.fontSizePt * 0.35),
        width: underlineWidthMm,
        height: 1.4,
        shape: "rect",
        fill: accent,
        stroke: "transparent",
        strokeWidth: 0,
        cornerRadius: 0,
      })
    );
  }
  return headingY + contentOffsetMm;
}

/**
 * Builds the Agenda pages' `"table"` layout (Classic) — a header row and one
 * ruled row per session (time • title • speakers), every cell its own
 * editable text element.
 *
 * Each row is as tall as its tallest cell, and the table continues onto
 * further pages; it used to size rows from the title alone (clipping a
 * wrapped time range) and stop after twelve sessions. Returns no pages when
 * there are no sessions.
 */
function buildAgendaTablePages(ctx: SeedContext): BrochurePage[] {
  const { theme, accent, fontFamily } = ctx;
  const content = buildAgendaSectionContent(ctx.input.sessions ?? []);
  if (content.rows.length === 0) return [];

  const frame = dataPageFrame(ctx);
  const bodyLeft = theme.margins.left;
  const bodyRight = PAGE_W - theme.margins.right;
  const contentWidth = bodyRight - bodyLeft;
  // Wide enough for "10:20 AM - 10:40 AM" on one line.
  const timeColW = 40;
  const speakersColW = Math.max(38, contentWidth * 0.26);
  const sessionColW = contentWidth - timeColW - speakersColW;
  const titleColX = bodyLeft + timeColW;
  const speakersColX = titleColX + sessionColW;

  const cellPad = 2;
  const headerRowH = 8;
  const bodyFontSize = 10;
  const bodyLineHeight = 1.3;
  const lineH = ptToMm(bodyFontSize) * bodyLineHeight;
  const gridLineW = 0.15;
  const gridColor = "#d4d4d4";

  const linesIn = (text: string, colW: number, bold = false): number =>
    wrapTextLines(text, (colW - cellPad * 2) * WRAP_FIT, bodyFontSize, bold).length;
  const rowHeights = content.rows.map((row) => {
    const lines = Math.max(
      linesIn(row.timeRangeText, timeColW, true),
      linesIn(row.title, sessionColW),
      row.speakerLine ? linesIn(row.speakerLine, speakersColW) : 1
    );
    return Math.max(headerRowH, cellPad * 2 + lines * lineH);
  });

  const pages: BrochurePage[] = [];
  let index = 0;
  while (index < content.rows.length) {
    const { elements, push } = createPusher();
    const tableTop = pushSectionHeader(push, ctx, "Agenda", 24, 10);

    // ── Header row ───────────────────────────────────────────────────
    push(rect(bodyLeft, tableTop, contentWidth, headerRowH, accent));
    const headerCells: Array<{ x: number; w: number; text: string }> = [
      { x: bodyLeft, w: timeColW, text: "Time" },
      { x: titleColX, w: sessionColW, text: "Session" },
      { x: speakersColX, w: speakersColW, text: "Speaker(s)" },
    ];
    for (const cell of headerCells) {
      push(
        newTextElement({
          x: cell.x + cellPad,
          y: tableTop,
          width: cell.w - cellPad * 2,
          height: headerRowH,
          content: cell.text,
          fontFamily,
          fontSize: bodyFontSize,
          fontWeight: "bold",
          color: "#ffffff",
          align: "left",
          lineHeight: 1,
          verticalAlign: "middle",
        })
      );
    }

    // ── Body rows — as many as fit this page (always at least one) ───
    const rowTops: number[] = [];
    let cursorY = tableTop + headerRowH;
    const firstRow = index;
    while (index < content.rows.length && (index === firstRow || cursorY + rowHeights[index] <= frame.bottom)) {
      const row = content.rows[index];
      const rowH = rowHeights[index];
      // One agenda row = time cell + title + speaker, grouped so a whole row
      // drags together instead of leaving its time behind.
      const pushRow = cardPusher(push);
      const cells: Array<{ x: number; w: number; text: string | undefined; bold: boolean; color: string }> = [
        { x: bodyLeft, w: timeColW, text: row.timeRangeText, bold: true, color: INK },
        { x: titleColX, w: sessionColW, text: row.title, bold: false, color: INK },
        { x: speakersColX, w: speakersColW, text: row.speakerLine, bold: false, color: "#5a5a5a" },
      ];
      for (const cell of cells) {
        if (!cell.text) continue;
        pushRow(
          newTextElement({
            x: cell.x + cellPad,
            y: cursorY + cellPad,
            width: cell.w - cellPad * 2,
            height: rowH - cellPad,
            content: cell.text,
            fontFamily,
            fontSize: bodyFontSize,
            fontWeight: cell.bold ? "bold" : "normal",
            color: cell.color,
            align: "left",
            lineHeight: bodyLineHeight,
          })
        );
      }
      rowTops.push(cursorY);
      cursorY += rowH;
      index += 1;
    }

    // ── Grid lines ───────────────────────────────────────────────────
    for (const y of [tableTop, ...rowTops, cursorY]) {
      push(rect(bodyLeft, y, contentWidth, gridLineW, gridColor));
    }
    for (const x of [bodyLeft, titleColX, speakersColX, bodyRight]) {
      push(rect(x, tableTop, gridLineW, cursorY - tableTop, gridColor));
    }

    frame.finish(push);
    pages.push(makePage("agenda", frame.background, elements));
  }
  return pages;
}

/**
 * Section header shared by every data page. Poster_Bold pages get the event
 * lockup and a large centered title on the off-white stock, so Speakers,
 * Sponsors and Venue read as part of the same brochure as the agenda;
 * every other theme keeps the Classic heading-and-underline. Returns the y
 * where the page's content starts.
 */
function pushSectionHeader(
  push: Push,
  ctx: SeedContext,
  text: string,
  underlineWidthMm: number,
  contentOffsetMm: number,
  posterMaxPt = 40
): number {
  if (!isPosterTheme(ctx.theme)) {
    return pushClassicSectionHeading(push, ctx.theme, text, ctx.accent, ctx.fontFamily, underlineWidthMm, contentOffsetMm);
  }
  const lockupBottom = pushLockup(push, ctx, INK, "paper");
  const titlePt = fitFontSizePt([text], 176, posterMaxPt, 18, true);
  const titleH = ptToMm(titlePt);
  const titleY = lockupBottom + 6;
  push(
    newTextElement({
      x: 5,
      y: titleY,
      width: PAGE_W - 10,
      height: titleH + 2,
      content: text,
      fontFamily: ctx.fontFamily,
      fontSize: titlePt,
      fontWeight: "bold",
      color: INK,
      align: "center",
      lineHeight: 1,
    })
  );
  return titleY + titleH + 9;
}

/** Background, bottom limit and closing strip for a data page, per theme. */
function dataPageFrame(ctx: SeedContext): { background: string; bottom: number; finish: (push: Push) => void } {
  if (isPosterTheme(ctx.theme)) {
    return { background: PAPER, bottom: CONTENT_BOTTOM, finish: (push) => push(bottomBar(ctx.accent)) };
  }
  return { background: "#ffffff", bottom: PAGE_H - ctx.theme.margins.bottom, finish: () => undefined };
}

// ─── Agenda — Poster_Bold timetable ────────────────────────────────────────

/** How a session's title bar is drawn on the timetable. */
type AgendaBarStyle = "accent" | "emphasis" | "outline";

/** Session types that are the programme itself rather than the gaps in it. */
const AGENDA_CONTENT_SESSION_TYPES = new Set(["talk", "keynote", "speaker", "panel", "workshop", "fireside", "qa"]);

/**
 * The reference agenda uses three bar styles, and they carry meaning:
 *
 *   - accent  — the frame of the day: registration, welcome, breaks, lunch,
 *               networking, awards. Also the fallback for a custom type.
 *   - emphasis (dark grey) — the content: panels, keynotes, roundtables.
 *   - outline (white bar, accent text) — partner / sponsor slots.
 *
 * `sessionType` arrives lowercased and trimmed. Custom organizer-typed
 * labels are matched by keyword so "Panel Discussion" or "Partner
 * Spotlight" land in the right style without being a preset.
 */
function agendaBarStyle(sessionType: string | undefined): AgendaBarStyle {
  if (!sessionType) return "accent";
  if (/sponsor|partner|spotlight|showcase/.test(sessionType)) return "outline";
  if (AGENDA_CONTENT_SESSION_TYPES.has(sessionType)) return "emphasis";
  if (/panel|keynote|roundtable|round table|workshop|fireside|discussion|masterclass/.test(sessionType)) return "emphasis";
  return "accent";
}

const AGENDA_COL_X = 11.4;
const AGENDA_COL_GAP = 2;
const AGENDA_COL_W = (PAGE_W - AGENDA_COL_X * 2 - AGENDA_COL_GAP) / 2;
const AGENDA_TIME_W = 21.6;
const AGENDA_CHIP_GAP = 0.5;
const AGENDA_BAR_W = AGENDA_COL_W - AGENDA_TIME_W - AGENDA_CHIP_GAP;
const AGENDA_BAR_PAD_X = 2.5;
const AGENDA_TITLE_PT = 8;
const AGENDA_TITLE_LH = 1.25;
const AGENDA_DESC_PT = 8;
const AGENDA_DESC_LH = 1.3;
const AGENDA_DESC_INSET = 2.3;
const AGENDA_DESC_W = AGENDA_COL_W - AGENDA_DESC_INSET * 2;
const AGENDA_BULLET_INDENT = 6;
const AGENDA_ROW_GAP = 1.4;

/** One measured piece of a session description. */
interface AgendaBlock {
  kind: "text" | "bullet" | "gap";
  text: string;
  height: number;
}

interface AgendaItem {
  row: AgendaRow;
  barH: number;
  blocks: AgendaBlock[];
  speakerH: number;
  /** Full height including the gap to the next item. */
  height: number;
}

/**
 * Splits a session description into paragraphs, bullets and paragraph gaps.
 * A line starting with `-`, `•`, `*` or `–` becomes a bullet with a hanging
 * indent — the reference lists each panel's talking points that way, and a
 * single text box can't indent wrapped lines. A blank line is a small gap.
 */
function agendaDescriptionBlocks(description: string): AgendaBlock[] {
  const blocks: AgendaBlock[] = [];
  let paragraph: string[] = [];
  const flush = (): void => {
    if (paragraph.length === 0) return;
    const text = paragraph.join("\n");
    blocks.push({
      kind: "text",
      text,
      height: estimateTextHeightMm(text, AGENDA_DESC_W * WRAP_FIT, AGENDA_DESC_PT, AGENDA_DESC_LH),
    });
    paragraph = [];
  };
  for (const raw of description.split("\n")) {
    const line = raw.trim();
    if (!line) {
      flush();
      if (blocks.length > 0 && blocks[blocks.length - 1].kind !== "gap") blocks.push({ kind: "gap", text: "", height: 1.7 });
      continue;
    }
    const bullet = /^[-•*–·]\s+(.+)$/.exec(line);
    if (bullet) {
      flush();
      blocks.push({
        kind: "bullet",
        text: bullet[1],
        height: estimateTextHeightMm(bullet[1], (AGENDA_DESC_W - AGENDA_BULLET_INDENT) * WRAP_FIT, AGENDA_DESC_PT, AGENDA_DESC_LH),
      });
    } else {
      paragraph.push(line);
    }
  }
  flush();
  while (blocks.length > 0 && blocks[blocks.length - 1].kind === "gap") blocks.pop();
  return blocks;
}

function measureAgendaItem(row: AgendaRow): AgendaItem {
  const titleLines = wrapTextLines(row.title, (AGENDA_BAR_W - AGENDA_BAR_PAD_X * 2) * WRAP_FIT, AGENDA_TITLE_PT, true).length;
  const barH = titleLines <= 1 ? 6.2 : titleLines * ptToMm(AGENDA_TITLE_PT) * AGENDA_TITLE_LH + 3.4;
  const blocks = row.description ? agendaDescriptionBlocks(row.description) : [];
  const blocksH = blocks.reduce((sum, b) => sum + b.height, 0);
  const speakerH = row.speakerLine
    ? estimateTextHeightMm(row.speakerLine, AGENDA_DESC_W * WRAP_FIT, 7.5, 1.25) + 1.2
    : 0;
  const bodyH = blocks.length > 0 || speakerH > 0 ? 1.8 + blocksH + speakerH + 2 : 0;
  return { row, barH, blocks, speakerH, height: barH + bodyH + AGENDA_ROW_GAP };
}

function pushAgendaItem(push: Push, ctx: SeedContext, item: AgendaItem, x: number, y: number): void {
  const { accent, fontFamily } = ctx;
  const { row, barH } = item;
  const style = agendaBarStyle(row.sessionType);
  // One session = time chip + title bar + description, grouped so the whole
  // entry drags together.
  const pushRow = cardPusher(push);

  pushRow(rect(x, y, AGENDA_TIME_W, barH, INK));
  pushRow(
    newTextElement({
      x,
      y,
      width: AGENDA_TIME_W,
      height: barH,
      content: row.startTimeText,
      fontFamily,
      fontSize: AGENDA_TITLE_PT,
      fontWeight: "bold",
      color: "#ffffff",
      align: "center",
      lineHeight: 1,
      verticalAlign: "middle",
    })
  );

  const barX = x + AGENDA_TIME_W + AGENDA_CHIP_GAP;
  if (style === "outline") {
    pushRow(rect(barX + 0.12, y + 0.12, AGENDA_BAR_W - 0.24, barH - 0.24, "#ffffff", 0, INK, 0.24));
  } else {
    pushRow(rect(barX, y, AGENDA_BAR_W, barH, style === "emphasis" ? "#555555" : accent));
  }
  pushRow(
    newTextElement({
      x: barX + AGENDA_BAR_PAD_X,
      y,
      width: AGENDA_BAR_W - AGENDA_BAR_PAD_X * 2,
      height: barH,
      content: row.title,
      fontFamily,
      fontSize: AGENDA_TITLE_PT,
      fontWeight: "bold",
      color: style === "outline" ? accent : "#ffffff",
      align: "left",
      lineHeight: AGENDA_TITLE_LH,
      verticalAlign: "middle",
    })
  );

  let cursorY = y + barH + 1.8;
  const textX = x + AGENDA_DESC_INSET;
  for (const block of item.blocks) {
    if (block.kind === "gap") {
      cursorY += block.height;
      continue;
    }
    const isBullet = block.kind === "bullet";
    if (isBullet) {
      pushRow(
        newTextElement({
          x: textX + 2.2,
          y: cursorY,
          width: 3,
          height: block.height,
          content: "•",
          fontFamily,
          fontSize: AGENDA_DESC_PT,
          fontWeight: "normal",
          color: INK,
          align: "left",
          lineHeight: AGENDA_DESC_LH,
        })
      );
    }
    pushRow(
      newTextElement({
        x: textX + (isBullet ? AGENDA_BULLET_INDENT : 0),
        y: cursorY,
        width: AGENDA_DESC_W - (isBullet ? AGENDA_BULLET_INDENT : 0),
        // A line of slack: a font wider than the estimate may wrap once more,
        // and Konva drops any line that doesn't fit the box.
        height: block.height + ptToMm(AGENDA_DESC_PT) * AGENDA_DESC_LH,
        content: block.text,
        fontFamily,
        fontSize: AGENDA_DESC_PT,
        fontWeight: "normal",
        color: INK,
        align: "left",
        lineHeight: AGENDA_DESC_LH,
      })
    );
    cursorY += block.height;
  }

  if (row.speakerLine) {
    pushRow(
      newTextElement({
        x: textX,
        y: cursorY + (item.blocks.length > 0 ? 1.2 : 0),
        width: AGENDA_DESC_W,
        height: item.speakerH + 2,
        content: row.speakerLine,
        fontFamily,
        fontSize: 7.5,
        fontWeight: "normal",
        fontStyle: "italic",
        color: "#5a5a5a",
        align: "left",
        lineHeight: 1.25,
      })
    );
  }
}

/**
 * Builds the Poster_Bold agenda — lockup, a huge "Event Agenda" title, and
 * two columns of sessions: a black start-time chip, a title bar styled by
 * session type (see `agendaBarStyle`), and the description beneath.
 *
 * Every session is measured first, so:
 *   - a day that fits one page is split where the two columns come out
 *     closest in height, instead of at the halfway session count (which
 *     put all the long panel descriptions in one column and ran it off the
 *     page);
 *   - a day that doesn't fit continues onto as many further pages as it
 *     needs, each column filled top to bottom.
 *
 * Returns no pages when there are no sessions.
 */
function buildAgendaTimetablePages(ctx: SeedContext): BrochurePage[] {
  const content = buildAgendaSectionContent(ctx.input.sessions ?? []);
  if (content.rows.length === 0) return [];
  const items = content.rows.map(measureAgendaItem);
  const columnX = [AGENDA_COL_X, AGENDA_COL_X + AGENDA_COL_W + AGENDA_COL_GAP];
  const pages: BrochurePage[] = [];

  const startPage = (first: boolean): { elements: BrochureElement[]; push: Push; top: number } => {
    const { elements, push } = createPusher();
    const top = pushSectionHeader(push, ctx, "Event Agenda", 0, 0, first ? 52 : 30);
    return { elements, push, top };
  };
  const finishPage = (elements: BrochureElement[], push: Push): void => {
    push(bottomBar(ctx.accent));
    pages.push(makePage("agenda", PAPER, elements));
  };
  const columnHeight = (from: number, to: number): number =>
    items.slice(from, to).reduce((sum, item) => sum + item.height, 0) - (to > from ? AGENDA_ROW_GAP : 0);

  // ── Fits on one page: balance the two columns ────────────────────
  const first = startPage(true);
  const available = CONTENT_BOTTOM - first.top;
  let split = items.length;
  let tallest = columnHeight(0, items.length);
  for (let k = 1; k < items.length; k += 1) {
    const height = Math.max(columnHeight(0, k), columnHeight(k, items.length));
    if (height < tallest) {
      tallest = height;
      split = k;
    }
  }
  if (tallest <= available) {
    const ranges: Array<[number, number]> = [
      [0, split],
      [split, items.length],
    ];
    ranges.forEach(([from, to], col) => {
      let y = first.top;
      for (let i = from; i < to; i += 1) {
        pushAgendaItem(first.push, ctx, items[i], columnX[col], y);
        y += items[i].height;
      }
    });
    finishPage(first.elements, first.push);
    return pages;
  }

  // ── Doesn't fit: fill column by column, page by page ─────────────
  let index = 0;
  let page = first;
  while (index < items.length) {
    for (let col = 0; col < 2 && index < items.length; col += 1) {
      let y = page.top;
      // An item taller than a whole column is still placed (at the top of
      // one) rather than looping forever looking for room.
      while (
        index < items.length &&
        (y === page.top || y + items[index].height - AGENDA_ROW_GAP <= CONTENT_BOTTOM)
      ) {
        pushAgendaItem(page.push, ctx, items[index], columnX[col], y);
        y += items[index].height;
        index += 1;
      }
    }
    finishPage(page.elements, page.push);
    if (index < items.length) page = startPage(false);
  }
  return pages;
}

// ─── Speakers ──────────────────────────────────────────────────────────────

/**
 * Builds the Speakers pages — a grid of speaker cards (photo + name +
 * subtitle + company), four across on Poster_Bold and two across on Classic.
 * Each field is a separate element so the organizer can retitle or remove
 * any of them. Continues onto further pages rather than dropping speakers
 * past the first eight. Returns no pages when there are no speakers.
 */
function buildSpeakersPages(ctx: SeedContext): BrochurePage[] {
  const { accent, fontFamily, theme } = ctx;
  const rows = buildSpeakerRows(ctx.input.speakers ?? []);
  if (rows.length === 0) return [];

  const poster = isPosterTheme(theme);
  const frame = dataPageFrame(ctx);
  const cols = poster ? 4 : 2;
  const gap = poster ? 4 : 8;
  const bodyLeft = poster ? 12 : 20;
  const cardW = (PAGE_W - bodyLeft * 2 - gap * (cols - 1)) / cols;
  const photoH = poster ? cardW : 44;
  const textH = 22;
  const cardH = photoH + textH + 2;
  const rowGap = poster ? 5 : 6;
  const textW = cardW - 4;
  const pages: BrochurePage[] = [];

  let index = 0;
  while (index < rows.length) {
    const { elements, push } = createPusher();
    const startY = pushSectionHeader(push, ctx, "Speakers", 24, 12) + (poster ? 0 : 2);
    const rowsPerPage = Math.max(1, Math.floor((frame.bottom - startY + rowGap) / (cardH + rowGap)));
    const shown = rows.slice(index, index + rowsPerPage * cols);
    index += shown.length;

    shown.forEach((row, i) => {
      const x = bodyLeft + (i % cols) * (cardW + gap);
      const y = startY + Math.floor(i / cols) * (cardH + rowGap);
      // One card = background + photo + name + subtitle + company, all sharing a
      // groupId so the tile selects, moves and resizes as a single object.
      const pushCard = cardPusher(push);

      pushCard(rect(x, y, cardW, cardH, poster ? "#ffffff" : "#f9fafb", 2, "#e5e7eb", 0.3));

      // Photo (URL image) or initial placeholder shape.
      if (row.photo.type === "url") {
        pushCard(newImageElement({ x, y, width: cardW, height: photoH, src: row.photo.url, fit: "cover", cornerRadius: 2 }));
      } else {
        pushCard(rect(x, y, cardW, photoH, accent, 2));
        pushCard(
          newTextElement({
            x,
            y,
            width: cardW,
            height: photoH,
            content: row.photo.initial,
            fontFamily,
            fontSize: 32,
            fontWeight: "bold",
            color: "#ffffff",
            align: "center",
            lineHeight: 1,
            verticalAlign: "middle",
          })
        );
      }

      const namePt = fitFontSizePt([row.name], textW * WRAP_FIT, poster ? 9.5 : 11, 6.5, true);
      pushCard(
        newTextElement({
          x: x + 2,
          y: y + photoH + 2.5,
          width: textW,
          height: 5.5,
          content: row.name,
          fontFamily,
          fontSize: namePt,
          fontWeight: "bold",
          color: poster ? INK : "#0a1429",
          align: "center",
          lineHeight: 1.1,
        })
      );
      const detailPt = poster ? 7.5 : 8.5;
      if (row.subtitleLine) {
        pushCard(
          newTextElement({
            x: x + 2,
            y: y + photoH + 8.5,
            width: textW,
            height: 7,
            content: row.subtitleLine,
            fontFamily,
            fontSize: detailPt,
            fontWeight: "normal",
            color: "#4b5563",
            align: "center",
            lineHeight: 1.1,
          })
        );
      }
      if (row.companyLine) {
        pushCard(
          newTextElement({
            x: x + 2,
            y: y + photoH + 16,
            width: textW,
            height: 5,
            content: row.companyLine,
            fontFamily,
            fontSize: fitFontSizePt([row.companyLine], textW * WRAP_FIT, detailPt, 6, false),
            fontWeight: "normal",
            color: accent,
            align: "center",
            lineHeight: 1.1,
          })
        );
      }
    });

    frame.finish(push);
    pages.push(makePage("speakers", frame.background, elements));
  }
  return pages;
}

// ─── Sponsors ──────────────────────────────────────────────────────────────

/** Builds the Sponsors page — tier headings followed by sponsor
 *  logos (or name text when no logo URL). Returns `null` when there
 *  are no sponsors. */
function buildSponsorsPage(ctx: SeedContext): BrochurePage | null {
  const { fontFamily, theme } = ctx;
  const sponsors = ctx.input.sponsors ?? [];
  if (sponsors.length === 0) return null;
  const groups = groupSponsorsByTierOrdered(sponsors);

  const poster = isPosterTheme(theme);
  const frame = dataPageFrame(ctx);
  const { elements, push } = createPusher();
  let cursorY = pushSectionHeader(push, ctx, "Sponsors", 24, 12);

  const bodyLeft = theme.margins.left;
  const bodyW = PAGE_W - theme.margins.left - theme.margins.right;
  const perRow = 3;
  const logoGap = 4;
  const logoW = (bodyW - logoGap * (perRow - 1)) / perRow;
  const logoH = 22;

  for (const group of groups) {
    // Tier heading (colored by tier accent).
    push(
      newTextElement({
        x: bodyLeft,
        y: cursorY,
        width: bodyW,
        height: 7,
        content: group.label.toUpperCase(),
        fontFamily,
        fontSize: 12,
        fontWeight: "bold",
        color: group.accentColor,
        align: "left",
        lineHeight: 1,
      })
    );
    push(rect(bodyLeft, cursorY + 8, 16, 0.8, group.accentColor));
    cursorY += 12;

    // Sponsor cards for this tier.
    const items = group.sponsors.slice(0, 12);
    for (let i = 0; i < items.length; i += 1) {
      const sponsor = items[i];
      const x = bodyLeft + (i % perRow) * (logoW + logoGap);
      const y = cursorY + Math.floor(i / perRow) * (logoH + 4);
      // Sponsor card = background surface + logo/text.
      const pushCard = cardPusher(push);

      // Card background so text logos have a distinct surface.
      pushCard(rect(x, y, logoW, logoH, poster ? "#ffffff" : "#f9fafb", 2, "#e5e7eb", 0.3));
      if (sponsor.logo.type === "url") {
        pushCard(
          newImageElement({ x: x + 2, y: y + 2, width: logoW - 4, height: logoH - 4, src: sponsor.logo.url, fit: "contain", cornerRadius: 0 })
        );
      } else {
        pushCard(
          newTextElement({
            x: x + 2,
            y,
            width: logoW - 4,
            height: logoH,
            content: sponsor.logo.text,
            fontFamily,
            fontSize: 10,
            fontWeight: "bold",
            color: poster ? INK : "#0a1429",
            align: "center",
            lineHeight: 1.1,
            verticalAlign: "middle",
          })
        );
      }
    }
    const rowsForGroup = Math.ceil(items.length / perRow);
    cursorY += rowsForGroup * (logoH + 4) + 4;
    if (cursorY > frame.bottom - 30) break; // stop before overflowing the page
  }

  frame.finish(push);
  return makePage("sponsors", frame.background, elements);
}

// ─── Venue & Logistics ─────────────────────────────────────────────────────

/** Builds the Venue & Logistics page — venue name, address, parking and
 *  transit notes, each a bold label over its value. Returns `null` when
 *  there's no meaningful content to show. */
function buildVenuePage(ctx: SeedContext): BrochurePage | null {
  const { fontFamily, theme } = ctx;
  if (!ctx.input.venueLogistics) return null;
  const content = buildVenueLogisticsContent(ctx.input.venueLogistics);
  if (!content) return null;

  const frame = dataPageFrame(ctx);
  const { elements, push } = createPusher();
  let cursorY = pushSectionHeader(push, ctx, "Venue & Logistics", 40, 12);

  const bodyLeft = theme.margins.left;
  const bodyW = PAGE_W - theme.margins.left - theme.margins.right;

  // Field order: Venue → Address → Parking → Transit. Each value is as tall
  // as its wrapped text, so a long address pushes the next label down
  // instead of printing over it.
  const addField = (label: string, body: string): void => {
    push(
      newTextElement({
        x: bodyLeft,
        y: cursorY,
        width: bodyW,
        height: 5,
        content: `${label}:`,
        fontFamily,
        fontSize: 11,
        fontWeight: "bold",
        color: INK,
        align: "left",
        lineHeight: 1,
      })
    );
    cursorY += 5.5;
    const bodyH = estimateTextHeightMm(body, bodyW * WRAP_FIT, 10, 1.4);
    push(
      newTextElement({
        x: bodyLeft,
        y: cursorY,
        width: bodyW,
        height: bodyH + 5,
        content: body,
        fontFamily,
        fontSize: 10,
        fontWeight: "normal",
        color: "#3c3c3c",
        align: "left",
        lineHeight: 1.4,
      })
    );
    cursorY += bodyH + 5;
  };

  if (content.venueName) addField("Venue", content.venueName);
  if (content.address) addField("Address", content.address);
  if (content.parkingNotes) addField("Parking", content.parkingNotes);
  if (content.transitNotes) addField("Transit", content.transitNotes);

  frame.finish(push);
  return makePage("venue", frame.background, elements);
}

// ─── Partnership / sponsorship packages ────────────────────────────────────

const PACKAGES_X = 17.5;
const PACKAGES_W = PAGE_W - PACKAGES_X - 11;
const PACKAGES_PT = 7.5;
const PACKAGES_LH = 1.25;
const PACKAGES_PAD = 1.5;
const PACKAGES_GRID = "#c9c9c9";
/** Most tiers a single table shows before the rest move to another page. */
const PACKAGES_MAX_TIERS = 4;

/**
 * Builds the partnership packages pages — a benefits × tiers comparison
 * table after the reference "Premium Partnership Packages" deck: an accent
 * two-line title with a rule running out to the organizer's logo, an accent
 * header row, hairline-ruled white rows with left-aligned cells, a red cross
 * for "not included", and a black "Cost" row.
 *
 * Rows are as tall as their tallest cell. A table with more rows than fit
 * continues on another page, and more than four tiers are split into
 * equal-sized tables — a column needs ~35mm to hold a phrase like
 * "Premium Branding Across Venue". Every cell is its own element. Returns
 * no pages when there's nothing to show.
 */
function buildSponsorshipPackagesPages(ctx: SeedContext): BrochurePage[] {
  const { input, accent, fontFamily } = ctx;
  if (!input.sponsorshipPackages) return [];
  const content = buildSponsorshipPackagesContent(input.sponsorshipPackages);
  if (!content) return [];

  const tablesNeeded = Math.ceil(content.tiers.length / PACKAGES_MAX_TIERS);
  const tiersPerTable = Math.ceil(content.tiers.length / tablesNeeded);
  const pages: BrochurePage[] = [];
  const lineH = ptToMm(PACKAGES_PT) * PACKAGES_LH;
  const hasCost = content.tiers.some((t) => t.price);

  for (let tierStart = 0; tierStart < content.tiers.length; tierStart += tiersPerTable) {
    const tiers = content.tiers.slice(tierStart, tierStart + tiersPerTable);
    const labelW = tiers.length <= 3 ? 45.5 : 38;
    const tierW = (PACKAGES_W - labelW) / tiers.length;
    const labelTextW = labelW - PACKAGES_PAD * 2;
    const cellTextW = tierW - PACKAGES_PAD * 2;
    const cellLines = (cell: SponsorshipCell | undefined): number =>
      cell?.kind === "text" ? wrapTextLines(cell.value, cellTextW * WRAP_FIT, PACKAGES_PT).length : 1;
    const rowHeights = content.benefits.map((benefit, r) => {
      const lines = Math.max(
        wrapTextLines(benefit, labelTextW * WRAP_FIT, PACKAGES_PT).length,
        ...tiers.map((t) => cellLines(t.cells[r]))
      );
      return Math.max(9.6, lines * lineH + 3.6);
    });
    const headerH = Math.max(
      9.5,
      Math.max(...tiers.map((t) => wrapTextLines(t.name, cellTextW * WRAP_FIT, PACKAGES_PT, true).length)) * lineH + 3.6
    );
    const costH = hasCost ? 9.5 : 0;

    let rowIndex = 0;
    while (rowIndex < content.benefits.length) {
      const { elements, push } = createPusher();
      const tableTop = pushPackagesHeader(push, ctx, content.title);
      const bodyLimit = PAGE_H - 12 - costH;

      // Header row.
      const pushHead = cardPusher(push);
      pushHead(rect(PACKAGES_X, tableTop, PACKAGES_W, headerH, accent));
      const headCells = ["Partner Categories", ...tiers.map((t) => t.name)];
      headCells.forEach((label, c) => {
        const x = c === 0 ? PACKAGES_X : PACKAGES_X + labelW + (c - 1) * tierW;
        if (c > 0) pushHead(rect(x - 0.1, tableTop, 0.2, headerH, "#ffffff"));
        pushHead(
          newTextElement({
            x: x + PACKAGES_PAD,
            y: tableTop,
            width: (c === 0 ? labelW : tierW) - PACKAGES_PAD * 2,
            height: headerH,
            content: label,
            fontFamily,
            fontSize: PACKAGES_PT,
            fontWeight: "bold",
            color: "#ffffff",
            align: "left",
            lineHeight: PACKAGES_LH,
            verticalAlign: "middle",
          })
        );
      });

      // Benefit rows — as many as fit this page (always at least one).
      const bodyTop = tableTop + headerH;
      let y = bodyTop;
      const firstRow = rowIndex;
      while (rowIndex < content.benefits.length && (rowIndex === firstRow || y + rowHeights[rowIndex] <= bodyLimit)) {
        const rowH = rowHeights[rowIndex];
        const pushRow = cardPusher(push);
        pushRow(rect(PACKAGES_X, y, PACKAGES_W, rowH, "#ffffff", 0, PACKAGES_GRID, 0.2));
        pushRow(
          newTextElement({
            x: PACKAGES_X + PACKAGES_PAD,
            y,
            width: labelTextW,
            height: rowH,
            content: content.benefits[rowIndex],
            fontFamily,
            fontSize: PACKAGES_PT,
            fontWeight: "normal",
            color: INK,
            align: "left",
            lineHeight: PACKAGES_LH,
            verticalAlign: "middle",
          })
        );
        tiers.forEach((tier, c) => {
          const cell = tier.cells[rowIndex];
          const x = PACKAGES_X + labelW + c * tierW + PACKAGES_PAD;
          if (cell?.kind === "text") {
            pushRow(
              newTextElement({
                x,
                y,
                width: cellTextW,
                height: rowH,
                content: cell.value,
                fontFamily,
                fontSize: PACKAGES_PT,
                fontWeight: "normal",
                color: INK,
                align: "left",
                lineHeight: PACKAGES_LH,
                verticalAlign: "middle",
              })
            );
          } else if (cell?.kind === "check" || cell?.kind === "cross") {
            const size = cell.kind === "check" ? 3.2 : 2.7;
            pushRow(
              newImageElement({
                x: x + 0.2,
                y: y + (rowH - size) / 2,
                width: size,
                height: size,
                src: cell.kind === "check" ? TICK_ICON : CROSS_ICON,
                fit: "contain",
              })
            );
          }
          // An empty cell stays blank, as in the reference.
        });
        y += rowH;
        rowIndex += 1;
      }

      // Column rules through the body rows.
      for (let c = 0; c < tiers.length; c += 1) {
        push(rect(PACKAGES_X + labelW + c * tierW - 0.1, bodyTop, 0.2, y - bodyTop, PACKAGES_GRID));
      }

      // Cost row closes the table, on its last page.
      if (hasCost && rowIndex >= content.benefits.length) {
        const pushCost = cardPusher(push);
        pushCost(rect(PACKAGES_X, y, PACKAGES_W, costH, INK));
        ["Cost", ...tiers.map((t) => t.price ?? "")].forEach((label, c) => {
          if (!label) return;
          pushCost(
            newTextElement({
              x: (c === 0 ? PACKAGES_X : PACKAGES_X + labelW + (c - 1) * tierW) + PACKAGES_PAD,
              y,
              width: (c === 0 ? labelW : tierW) - PACKAGES_PAD * 2,
              height: costH,
              content: label,
              fontFamily,
              fontSize: fitFontSizePt([label], ((c === 0 ? labelW : tierW) - PACKAGES_PAD * 2) * WRAP_FIT, PACKAGES_PT, 5.5, true),
              fontWeight: "bold",
              color: "#ffffff",
              align: "left",
              lineHeight: 1,
              verticalAlign: "middle",
            })
          );
        });
      }

      pages.push(makePage("sponsorship", "#ffffff", elements));
    }
  }
  return pages;
}

/** Title block of a packages page: the accent two-line title, the rule that
 *  runs from it to the organizer logo, and the logo itself. Returns the y
 *  where the table starts. */
function pushPackagesHeader(push: Push, ctx: SeedContext, title: string): number {
  const { input, accent, fontFamily } = ctx;
  const titlePt = 25;
  const titleLH = 0.98;
  const titleW = 112;
  const titleTop = 21;
  const lines = wrapTextLines(title, titleW * WRAP_FIT, titlePt, true);
  const titleH = lines.length * ptToMm(titlePt) * titleLH;
  push(
    newTextElement({
      x: PACKAGES_X,
      y: titleTop,
      width: titleW,
      height: titleH + 3,
      content: lines.join("\n"),
      fontFamily,
      fontSize: titlePt,
      fontWeight: "bold",
      color: accent,
      align: "left",
      lineHeight: titleLH,
    })
  );

  const right = PACKAGES_X + PACKAGES_W;
  const ruleY = titleTop + ptToMm(titlePt) * 0.5;
  let ruleEnd = right;
  if (input.organizerLogoUrl) {
    const logoW = 36;
    const logoH = 9;
    push(
      newImageElement({ x: right - logoW, y: ruleY - logoH / 2, width: logoW, height: logoH, src: input.organizerLogoUrl, fit: "contain", focalX: 1 })
    );
    ruleEnd = right - logoW - 4;
  }
  const ruleStart = PACKAGES_X + estimateTextWidthMm(lines[0] ?? "", titlePt, true) + 6;
  if (ruleEnd - ruleStart > 8) push(rect(ruleStart, ruleY, ruleEnd - ruleStart, 0.35, accent));

  return titleTop + titleH + 7;
}
