/**
 * Template presets for the brochure editor. Each preset takes event-
 * provided values (title, date, venue, cover image URL, organizer
 * branding, abstract text, learning outcomes, etc.) and returns a
 * fully-populated `Brochure_Document` — every text block, image, and
 * shape from the corresponding jsPDF theme is expressed as a separate
 * editable element the organizer can select and modify.
 *
 * Two themes ship today:
 *  - Poster_Bold (DevOps Connect look): white cover + orange accents +
 *    editorial content pages.
 *  - Corporate_Bold (Finance 6.0 look): deep-purple gradient cover +
 *    black content pages with purple accents.
 *
 * Both seeds emit the full multi-page brochure: cover, abstract (with
 * learning outcomes grid), why-sponsor / focus-of-summit numbered
 * list, and a pricing / speakers-summary closing page. Adding /
 * removing pages once loaded is a no-op on this file — the editor
 * mutates its own document tree.
 */
import {
  A4_HEIGHT_MM,
  A4_WIDTH_MM,
  newDocument,
  newImageElement,
  newPage,
  newPillElement,
  newShapeElement,
  newTextElement,
  type BrochureDocument,
  type BrochureElement,
  type BrochurePage,
} from "./editor-document";
import type { BrochureSectionId, BrochureTheme } from "../brochure-templates";
import {
  buildAgendaSectionContent,
  buildSpeakerRows,
  buildSponsorshipPackagesContent,
  buildVenueLogisticsContent,
  groupSponsorsByTierOrdered,
  type AgendaRow,
  type AgendaSessionInput,
  type SpeakerInput,
  type SponsorInput,
  type SponsorshipPackagesInput,
  type VenueLogisticsInput,
} from "../brochure-sections";

/**
 * Bump this integer whenever `seedBrochureDocument`'s visual output
 * changes in a way that should invalidate a previously-saved editor
 * document (layout numbers, heading sizes, field order/labels, table
 * styling, etc — anything that makes an OLD saved document look
 * different from what a FRESH seed now produces for the same input).
 *
 * This is the fix for a real structural bug: `BrochureEditorDialog`
 * always prefers a saved `Brochure_Document` (from Supabase) over a
 * fresh seed, with no way to tell whether that saved snapshot was
 * generated by an OLDER version of this file. Every time this seed's
 * layout was corrected to better match the live jsPDF preview, any
 * organizer who had already opened (and especially saved from) the
 * editor kept seeing the stale, pre-fix layout indefinitely — the
 * live preview always regenerates from current code, but the saved
 * editor document does not, so the two silently diverged forever with
 * no way for the organizer to know why or fix it themselves.
 *
 * `BrochureEditorDialog` compares this constant against the version
 * stamped on a saved document (`brochurePrefs.editorDocument.
 * templateVersion` in `page-form/types.ts`) and automatically falls
 * back to a fresh seed when the saved version is missing or older —
 * see the `isStaleSavedDocument` check there. A saved document from
 * before this constant existed has no `templateVersion` field at all,
 * which is treated as "older than any real version" (i.e. always
 * stale), since every pre-versioning seed output is exactly the kind
 * of drift this mechanism exists to catch.
 */
/**
 * Version history:
 *   1 — Initial versioned seed.
 *   2 — Poster_Bold layout aligned to the DevOps Connect reference:
 *       - Cover: top logo + huge title + subtitle + two outlined
 *         date/venue pill-chips + hero image + orange "shoulder"
 *         bleeds + white rounded footer band with producer credit +
 *         social icons.
 *       - Agenda ("timetable-cards" layout): two-column chronological
 *         split, per-row colored bar (black for keynote/panel/fireside/
 *         workshop, accent for everything else), full-width title bar,
 *         description body directly below the row on white with dark
 *         text. Big centered "Event Agenda" heading + top logo.
 */
export const EDITOR_SEED_VERSION = 2;

/** Input for template pre-loading. Mirrors the essential fields the
 *  jsPDF renderer already receives via `BrochureGenerationInput`, so a
 *  seed built from the SAME source data produces a document matching
 *  the live preview page-for-page (Requirement: editor/preview parity).
 */
export interface TemplateSeedInput {
  eventTitle: string;
  /** Human-readable date range, e.g. "12 Aug 2026 | 09:00 AM onwards". */
  dateText: string;
  /** Human-readable venue name / city. */
  venueText: string;
  /** Cover hero image URL. Empty string is allowed; the canvas shows a
   *  placeholder gray box until the organizer picks one. */
  coverImageUrl: string;
  /** Small logo shown near the top of the cover. */
  logoUrl?: string;
  /** Producer/organizer logo shown at the cover bottom-left. */
  organizerLogoUrl?: string;
  /** Optional tagline pill (e.g. "The Next Big Shift"). */
  coverTagline?: string;
  /** Optional short chip labels (e.g. ["Autonomy", "Governance", "Capital"]). */
  coverPills?: string[];
  /** Optional cover-footer social icons — same shape as
   *  `posterContent.socialLinks` on the jsPDF pipeline. Rendered as a
   *  right-aligned row of colored circles on the cover's footer band. */
  socialLinks?: Array<{
    platform: "linkedin" | "instagram" | "facebook" | "twitter";
    url?: string;
  }>;
  /** Optional abstract body copy for the abstract page. */
  abstract?: string;
  /** Optional featured body copy for the abstract page. */
  featured?: string;
  /** Optional learning-outcomes chips (up to 6). */
  learningOutcomes?: string[];
  /** Optional numbered value-prop items for the "Why Sponsor?" or
   *  "Focus of the Summit" page. */
  numberedItems?: string[];
  /** Pricing cards for the Poster_Bold Pricing page — same source as
   *  `brochure-pdf.ts`'s `posterContent.pricing.cards`. */
  pricingCards?: Array<{ title: string; subtitle?: string | null; price: string; discounts?: string[] | null }>;
  /** Whether to render the blank registration-form grid below the
   *  pricing cards — same source as `posterContent.pricing.showRegistrationForm`. */
  showRegistrationForm?: boolean;
  /** Resolved accent color (theme default with any organizer override
   *  already applied) — callers MUST pass `resolveBrochureTheme(...)`'s
   *  `accentColor`, not a raw theme default, so an organizer's color
   *  override is reflected in the editor exactly like the live preview. */
  accentColor?: string;
  /** Primary text color for cover title (contrasting the background). */
  titleColor?: string;
  /** Resolved font family (theme default with any organizer override
   *  already applied) — same precedence note as `accentColor`. */
  fontFamily?: string;

  // ── Content pages (Classic seed) ────────────────────────────────
  //
  // The Classic seed matches the jsPDF preview's section layout
  // (Cover + Agenda + Speakers + Sponsors + Venue) rather than the
  // legacy Poster_Bold seed's abstract/why-sponsor pages, so the
  // editor and the preview show the SAME set of pages. When any of
  // these arrays is absent or empty, the corresponding page is
  // skipped entirely (the organizer can still add it manually via
  // the "add page" control in the pages bar).
  sessions?: AgendaSessionInput[];
  speakers?: SpeakerInput[];
  sponsors?: SponsorInput[];
  venueLogistics?: VenueLogisticsInput;
  /** Benefits × tiers sponsorship comparison table — same source as the
   *  jsPDF preview's `sponsorshipPackages` section content. Omitted
   *  (undefined/null benefits or tiers) means the page is skipped. */
  sponsorshipPackages?: SponsorshipPackagesInput;
}

// ─── Unified section-driven seed (editor/preview parity) ────────────────────
//
// `seedBrochureDocument` is the ONE seed entry point used by
// `BrochureEditorDialog`. It walks the SAME resolved section id list the
// jsPDF preview walks (`resolveSectionLayout(sectionLayout)` in the
// caller), building one editable page per section — so the editor can
// never show a different set of pages than the preview/export, and a
// section that yields no content is skipped exactly like
// `buildBrochureDocument` skips it. Unsupported section ids
// (`whoShouldAttend`, `solutionProviders`, `highlights` — Corporate_Bold-
// only pages with no editor page builder yet) are skipped rather than
// throwing, so a legacy Corporate_Bold config still opens with whatever
// subset of its pages the editor can represent.
export function seedBrochureDocument(
  input: TemplateSeedInput,
  theme: BrochureTheme,
  resolvedSectionIds: BrochureSectionId[]
): BrochureDocument {
  const accent = input.accentColor ?? theme.defaultColors.accentColor;
  const fontFamily = input.fontFamily ?? theme.defaultColors.fontFamily ?? "Poppins";
  // Cover title color is genuinely theme-dependent (poster-bold's cover
  // page is always white-bg/black-text; corporate-bold's is always a
  // dark gradient/white-text) — mirrors `drawPosterBoldCover` /
  // `drawCorporateBoldCover`'s hardcoded choices exactly.
  const isCorporateBold = theme.id === "corporate-bold";
  const coverTitleColor = input.titleColor ?? (isCorporateBold ? "#ffffff" : "#0a1429");

  const doc = newDocument(input.eventTitle || "Untitled Brochure");
  const pages: BrochurePage[] = [];

  for (const id of resolvedSectionIds) {
    const page = buildEditorPageForSection(id, input, theme, accent, fontFamily, coverTitleColor, isCorporateBold);
    if (page) pages.push(page);
  }

  return {
    ...doc,
    pages: pages.length > 0 ? pages : [newPage()],
    templateVersion: EDITOR_SEED_VERSION,
  };
}

function buildEditorPageForSection(
  id: BrochureSectionId,
  input: TemplateSeedInput,
  theme: BrochureTheme,
  accent: string,
  fontFamily: string,
  coverTitleColor: string,
  isCorporateBold: boolean
): BrochurePage | null {
  switch (id) {
    case "cover":
      return isCorporateBold
        ? buildCorporateBoldCoverPage(input, accent, coverTitleColor, fontFamily)
        : buildPosterBoldCoverPage(input, accent, coverTitleColor, fontFamily);
    case "agenda":
      return theme.agenda.layout === "timetable-cards"
        ? buildAgendaTimetableCardsPage(input, theme, accent, fontFamily)
        : buildAgendaPage(input, theme, accent, fontFamily);
    case "speakers":
      return buildSpeakersPage(input.speakers ?? [], theme, accent, fontFamily);
    case "sponsors":
      return buildSponsorsPage(input.sponsors ?? [], theme, accent, fontFamily);
    case "venueLogistics":
      return buildVenuePage(input.venueLogistics, theme, accent, fontFamily);
    case "abstract":
      return buildAbstractPage(input, accent, fontFamily);
    case "whySponsor":
      return buildNumberedListPage(input.numberedItems ?? [], "Why Sponsor?", accent, fontFamily, input.logoUrl);
    case "pricing":
      return buildPricingPage(input, accent, fontFamily);
    case "focusOfSummit":
      return buildNumberedListPage(input.numberedItems ?? [], "Focus of the Summit", accent, fontFamily, input.logoUrl);
    case "sponsorshipPackages":
      return buildSponsorshipPackagesPage(input.sponsorshipPackages, theme, accent, fontFamily);
    // Corporate_Bold-only sections with no editor page builder yet —
    // skip rather than throw, matching the jsPDF renderer's own
    // null-content skip contract.
    case "whoShouldAttend":
    case "solutionProviders":
    case "highlights":
      return null;
    default:
      return null;
  }
}

// ─── Cover page builders ───────────────────────────────────────────────────

function buildPosterBoldCoverPage(
  input: TemplateSeedInput,
  accent: string,
  titleColor: string,
  fontFamily: string
): BrochurePage {
  // Mirrors `drawPosterBoldCover` in `brochure-pdf.ts` structurally so
  // the editor and the live preview render the same cover layout for
  // every event, then lets the organizer pick / move / recolor any
  // single element like Canva. Every text, chip, image, and shape is
  // an independent editable element — no "locked" background image
  // that hides the composition.
  const pageW = A4_WIDTH_MM;
  const pageH = A4_HEIGHT_MM;
  const marginX = 20;
  const elements: BrochureElement[] = [];
  const push = (el: BrochureElement) => {
    el.zIndex = elements.length;
    elements.push(el);
  };

  // ── 1. Top wordmark (centered) ────────────────────────────────────
  let cursorY = 18;
  if (input.logoUrl) {
    const logoW = 60;
    const logoH = 18;
    push(
      newImageElement({
        x: pageW / 2 - logoW / 2,
        y: cursorY,
        width: logoW,
        height: logoH,
        src: input.logoUrl,
        fit: "contain",
      })
    );
    cursorY += logoH + 4;
  } else {
    cursorY += 4;
  }

  // ── 2. Huge two-line title ───────────────────────────────────────
  const titleH = 40;
  push(
    newTextElement({
      x: marginX,
      y: cursorY,
      width: pageW - marginX * 2,
      height: titleH,
      content: input.eventTitle,
      fontFamily,
      fontSize: 40,
      fontWeight: "bold",
      color: titleColor,
      align: "center",
      lineHeight: 1.05,
    })
  );
  cursorY += titleH + 2;

  // ── 3. Subtitle (from coverTagline) ─────────────────────────────
  const subtitle = input.coverTagline?.trim();
  if (subtitle) {
    push(
      newTextElement({
        x: marginX,
        y: cursorY,
        width: pageW - marginX * 2,
        height: 14,
        content: subtitle,
        fontFamily,
        fontSize: 14,
        fontWeight: "normal",
        color: "#1e1e1e",
        align: "center",
        lineHeight: 1.2,
      })
    );
    cursorY += 16;
  }

  // ── 4. Two outlined pill-chips side by side (date | venue) ──────
  //
  // Both chips are centered as a horizontal row; venue chip is omitted
  // when the event has no venue set. Chip widths are estimated from
  // character count (~1.9mm per char at 10pt in a sans-serif with
  // 6mm side-padding), close enough to visually match the jsPDF
  // `doc.getTextWidth`-driven sizes without pulling a Canva-scale text
  // measurement dependency into the editor seed.
  const chipH = 10;
  const chipPadX = 6;
  const chipGap = 6;
  const estimateChipWidth = (text: string): number =>
    Math.max(28, text.length * 1.9 + chipPadX * 2);
  const chips: string[] = [input.dateText];
  if (input.venueText) chips.push(input.venueText);
  const chipWidths = chips.map(estimateChipWidth);
  const totalChipsW =
    chipWidths.reduce((a, b) => a + b, 0) + chipGap * (chips.length - 1);
  let chipX = pageW / 2 - totalChipsW / 2;
  const chipY = cursorY + 2;
  for (let i = 0; i < chips.length; i += 1) {
    push(
      newPillElement({
        x: chipX,
        y: chipY,
        width: chipWidths[i],
        height: chipH,
        text: chips[i],
        fontFamily,
        fontSize: 10,
        textColor: "#000000",
        fillColor: "#ffffff",
        strokeColor: "#000000",
        strokeWidth: 0.4,
      })
    );
    chipX += chipWidths[i] + chipGap;
  }
  cursorY = chipY + chipH + 6;

  // ── 5. Hero image (fills middle of page) ────────────────────────
  //
  // Reserves the footer-band + shoulder height so the image doesn't
  // spill into the "M" silhouette below.
  const footerBandH = 30;
  const shoulderH = 12;
  const heroTop = cursorY;
  const heroBottom = pageH - footerBandH - shoulderH * 0.4;
  const heroH = Math.max(20, heroBottom - heroTop);
  const hasCover =
    typeof input.coverImageUrl === "string" && input.coverImageUrl.trim().length > 0;
  if (hasCover) {
    push(
      newImageElement({
        x: 0,
        y: heroTop,
        width: pageW,
        height: heroH,
        src: input.coverImageUrl,
        fit: "cover",
        cornerRadius: 0,
      })
    );
  } else {
    // No banner uploaded — draw a placeholder image element so the
    // organizer sees "click to add source" affordance right where the
    // cover image will eventually live (same placeholder ImageBody
    // renders on the Konva canvas for an empty `src`).
    push(
      newImageElement({
        x: 0,
        y: heroTop,
        width: pageW,
        height: heroH,
        src: "",
        fit: "cover",
        cornerRadius: 0,
      })
    );
  }

  // ── 6. Orange "shoulder" bleeds + white rounded footer ─────────
  //
  // Draws a full-width accent-colored strip beneath the hero, then a
  // white rounded rectangle on top of it with a large corner radius
  // so the accent color forms two visible "shoulders" flanking the
  // rounded white notch — matching the reference brochure's cover
  // silhouette. Kept as separate editable shape elements (not a single
  // baked path) so the organizer can restyle the accent color, tune
  // the radius, or delete the effect entirely.
  const shoulderTop = pageH - footerBandH - shoulderH;
  push(
    newShapeElement({
      x: 0,
      y: shoulderTop,
      width: pageW,
      height: shoulderH + footerBandH,
      shape: "rect",
      fill: accent,
      stroke: "transparent",
      strokeWidth: 0,
      cornerRadius: 0,
    })
  );
  // White rounded overlay — corners curve UP into the accent band.
  push(
    newShapeElement({
      x: 0,
      y: pageH - footerBandH,
      width: pageW,
      height: footerBandH,
      shape: "rect",
      fill: "#ffffff",
      stroke: "transparent",
      strokeWidth: 0,
      cornerRadius: shoulderH,
    })
  );

  // ── 7. Footer content (left: producer credit + logo; right: social) ──
  const footerTop = pageH - footerBandH;
  push(
    newTextElement({
      x: marginX,
      y: footerTop + 6,
      width: 100,
      height: 5,
      content: "Conceptualized & Organized by",
      fontFamily,
      fontSize: 9,
      fontWeight: "bold",
      color: "#000000",
      align: "left",
      lineHeight: 1,
    })
  );
  if (input.organizerLogoUrl) {
    push(
      newImageElement({
        x: marginX,
        y: footerTop + 12,
        width: 44,
        height: 16,
        src: input.organizerLogoUrl,
        fit: "contain",
      })
    );
  }
  push(
    newTextElement({
      x: pageW - marginX - 70,
      y: footerTop + 6,
      width: 70,
      height: 5,
      content: "Follow us on social media",
      fontFamily,
      fontSize: 9,
      fontWeight: "bold",
      color: "#000000",
      align: "right",
      lineHeight: 1,
    })
  );

  // Social icons — one small colored circle per configured platform,
  // matching `drawPosterBoldCover`'s icon-strip layout. Uses tinted
  // circles as a stand-in for real platform glyphs since the editor's
  // canvas has no icon-font pipeline; the organizer can replace any
  // circle with a real logo image element via the palette.
  const socials = input.socialLinks ?? [];
  if (socials.length > 0) {
    const iconSize = 7;
    const iconGap = 4;
    const totalRowW = socials.length * iconSize + (socials.length - 1) * iconGap;
    let iconX = pageW - marginX - totalRowW;
    const iconY = footerTop + 14;
    const brandColors: Record<string, string> = {
      linkedin: "#0a66c2",
      instagram: "#e1306c",
      facebook: "#1877f2",
      twitter: "#1da1f2",
    };
    const brandInitials: Record<string, string> = {
      linkedin: "in",
      instagram: "ig",
      facebook: "f",
      twitter: "x",
    };
    for (const s of socials) {
      const bg = brandColors[s.platform] ?? "#000000";
      push(
        newShapeElement({
          x: iconX,
          y: iconY,
          width: iconSize,
          height: iconSize,
          shape: "ellipse",
          fill: bg,
          stroke: "transparent",
          strokeWidth: 0,
          cornerRadius: 0,
        })
      );
      push(
        newTextElement({
          x: iconX,
          y: iconY + 1.5,
          width: iconSize,
          height: iconSize,
          content: brandInitials[s.platform] ?? "•",
          fontFamily,
          fontSize: 5,
          fontWeight: "bold",
          color: "#ffffff",
          align: "center",
          lineHeight: 1,
        })
      );
      iconX += iconSize + iconGap;
    }
  }

  return {
    id: `page-cover-${Math.random().toString(36).slice(2, 8)}`,
    width: A4_WIDTH_MM,
    height: A4_HEIGHT_MM,
    background: { type: "solid", color: "#ffffff" },
    elements,
  };
}

function buildCorporateBoldCoverPage(
  input: TemplateSeedInput,
  accent: string,
  titleColor: string,
  fontFamily: string
): BrochurePage {
  // Reuse the Poster Bold cover geometry but with a gradient bg + white text.
  const page = buildPosterBoldCoverPage(input, accent, titleColor, fontFamily);
  page.background = { type: "gradient", top: "#1a0730", bottom: "#3a1152" };
  return page;
}

// ─── Abstract page (used by both themes) ───────────────────────────────────

function buildAbstractPage(input: TemplateSeedInput, accent: string, fontFamily: string): BrochurePage | null {
  const abstractText = input.abstract?.trim();
  const featuredText = input.featured?.trim();
  const outcomes = (input.learningOutcomes ?? []).filter((s) => s && s.trim());
  if (!abstractText && !featuredText && outcomes.length === 0) return null;

  const pageW = A4_WIDTH_MM;
  const elements: BrochureElement[] = [];
  const push = (el: BrochureElement) => {
    el.zIndex = elements.length;
    elements.push(el);
  };
  const textColor = "#ffffff";

  // Full-bleed accent-colored background, matching `drawAbstractSection`'s
  // orange (or theme-accent) full-page fill.
  const bgColor = accent;
  void textColor;

  // Centered wordmark logo at the top (matches `drawPosterHeaderLogo`
  // called from `drawAbstractSection` in `brochure-pdf.ts`). When no
  // logo is configured, the header area collapses so the ABSTRACT pill
  // still starts near the top of the page.
  let cursorY = 20;
  if (input.logoUrl) {
    const logoW = 50;
    const logoH = 16;
    push(
      newImageElement({
        x: pageW / 2 - logoW / 2,
        y: cursorY,
        width: logoW,
        height: logoH,
        src: input.logoUrl,
        fit: "contain",
      })
    );
    cursorY += logoH + 8;
  } else {
    cursorY += 4;
  }

  // Card renderer shared by the Abstract/Featured blocks — matches
  // `drawAbstractSection`'s `drawCardBlock`: a black heading pill
  // floating above a white body card.
  const pushCardBlock = (heading: string, body: string) => {
    const cardX = 20;
    const cardW = pageW - 40;
    const headingPillW = 42;
    const headingPillH = 10;
    push(
      newPillElement({
        x: pageW / 2 - headingPillW / 2,
        y: cursorY,
        width: headingPillW,
        height: headingPillH,
        text: heading,
        fontFamily,
        fontSize: 9,
        textColor: "#ffffff",
        fillColor: "#000000",
        strokeColor: "transparent",
        strokeWidth: 0,
      })
    );
    const cardY = cursorY + headingPillH / 2;
    const cardH = 46;
    push(
      newShapeElement({
        x: cardX,
        y: cardY,
        width: cardW,
        height: cardH,
        shape: "rect",
        fill: "#ffffff",
        stroke: "transparent",
        strokeWidth: 0,
        cornerRadius: 6,
      })
    );
    push(
      newTextElement({
        x: cardX + 8,
        y: cardY + headingPillH / 2 + 6,
        width: cardW - 16,
        height: cardH - headingPillH / 2 - 10,
        content: body,
        fontFamily,
        fontSize: 10.5,
        fontWeight: "normal",
        color: "#000000",
        align: "center",
        lineHeight: 1.35,
      })
    );
    cursorY = cardY + cardH + 8;
  };

  if (abstractText) pushCardBlock("ABSTRACT", abstractText);
  if (featuredText) pushCardBlock("Featured", featuredText);

  // Learning outcomes grid — two-column dark rounded chips.
  if (outcomes.length > 0) {
    push(
      newTextElement({
        x: 20,
        y: cursorY,
        width: pageW - 40,
        height: 10,
        content: "LEARNING OUTCOMES",
        fontFamily,
        fontSize: 16,
        fontWeight: "bold",
        color: "#000000",
        align: "center",
        lineHeight: 1,
      })
    );
    const gridTop = cursorY + 12;
    const cols = 2;
    const gap = 4;
    const chipW = (pageW - 40 - gap * (cols - 1)) / cols;
    const chipH = 18;
    for (let i = 0; i < Math.min(outcomes.length, 6); i += 1) {
      const col = i % cols;
      const row = Math.floor(i / cols);
      const x = 20 + col * (chipW + gap);
      const y = gridTop + row * (chipH + gap);
      push(
        newShapeElement({
          x,
          y,
          width: chipW,
          height: chipH,
          shape: "rect",
          fill: "#000000",
          stroke: "transparent",
          strokeWidth: 0,
          cornerRadius: 4,
        })
      );
      push(
        newTextElement({
          x: x,
          y: y + chipH / 2 - 3,
          width: chipW,
          height: chipH,
          content: outcomes[i],
          fontFamily,
          fontSize: 10,
          fontWeight: "bold",
          color: "#ffffff",
          align: "center",
          lineHeight: 1.2,
        })
      );
    }
  }

  return {
    id: `page-abstract-${Math.random().toString(36).slice(2, 8)}`,
    width: A4_WIDTH_MM,
    height: A4_HEIGHT_MM,
    background: { type: "solid", color: bgColor },
    elements,
  };
}

// ─── Numbered list page (Why Sponsor / Focus of Summit) ────────────────────
//
// Matches `drawWhySponsorSection`: full-bleed black background, huge
// white title, numbered rows = full-height accent-colored number badge
// + an outlined (accent stroke, no fill) body row with white text.
// Returns `null` when there are zero non-empty items, mirroring
// `buildWhySponsorSectionContent`'s null-return contract.

function buildNumberedListPage(
  items: string[],
  title: string,
  accent: string,
  fontFamily: string,
  logoUrl?: string,
): BrochurePage | null {
  const clean = items.filter((s) => s && s.trim().length > 0);
  if (clean.length === 0) return null;

  const pageW = A4_WIDTH_MM;
  const elements: BrochureElement[] = [];
  const push = (el: BrochureElement) => {
    el.zIndex = elements.length;
    elements.push(el);
  };

  // Top centered logo (white on the black background), matches
  // `drawPosterHeaderLogo` called from `drawWhySponsorSection`. When
  // no logo is configured, the title just starts a bit higher.
  let headerBottom = 20;
  if (logoUrl) {
    const logoW = 50;
    const logoH = 16;
    push(
      newImageElement({
        x: pageW / 2 - logoW / 2,
        y: headerBottom,
        width: logoW,
        height: logoH,
        src: logoUrl,
        fit: "contain",
      })
    );
    headerBottom += logoH + 6;
  } else {
    headerBottom += 6;
  }

  push(
    newTextElement({
      x: 20,
      y: headerBottom,
      width: pageW - 40,
      height: 20,
      content: title.toUpperCase(),
      fontFamily,
      fontSize: 32,
      fontWeight: "bold",
      color: "#ffffff",
      align: "center",
      lineHeight: 1,
    })
  );

  const rowH = 24;
  const rowGap = 4;
  const badgeW = 18;
  // Push the numbered rows below the header (logo + title) — using the
  // dynamic `headerBottom` computed above keeps spacing tight whether
  // a logo is present or not.
  const startY = headerBottom + 26;

  for (let i = 0; i < Math.min(clean.length, 8); i += 1) {
    const y = startY + i * (rowH + rowGap);
    // Number badge.
    push(
      newShapeElement({
        x: 20,
        y,
        width: badgeW,
        height: rowH,
        shape: "rect",
        fill: accent,
        stroke: "transparent",
        strokeWidth: 0,
        cornerRadius: 0,
      })
    );
    push(
      newTextElement({
        x: 20,
        y: y + rowH / 2 - 4,
        width: badgeW,
        height: rowH,
        content: String(i + 1),
        fontFamily,
        fontSize: 16,
        fontWeight: "bold",
        color: "#ffffff",
        align: "center",
        lineHeight: 1,
      })
    );
    // Item body — outline row.
    push(
      newShapeElement({
        x: 20,
        y,
        width: pageW - 40,
        height: rowH,
        shape: "rect",
        fill: "transparent",
        stroke: accent,
        strokeWidth: 0.4,
        cornerRadius: 0,
      })
    );
    push(
      newTextElement({
        x: 20 + badgeW + 6,
        y: y + 3,
        width: pageW - 40 - badgeW - 8,
        height: rowH - 6,
        content: clean[i],
        fontFamily,
        fontSize: 10,
        fontWeight: "normal",
        color: "#ffffff",
        align: "left",
        lineHeight: 1.35,
      })
    );
  }

  return {
    id: `page-list-${Math.random().toString(36).slice(2, 8)}`,
    width: A4_WIDTH_MM,
    height: A4_HEIGHT_MM,
    background: { type: "solid", color: "#000000" },
    elements,
  };
}

// ─── Pricing page (Poster_Bold, page 5) ─────────────────────────────────────
//
// Matches `drawPricingSection`: full-bleed accent-colored background,
// one or two columns of white pricing cards (title, subtitle, huge
// price, discount bullets), plus an optional blank registration-form
// grid. Returns `null` when there are zero cards AND the registration
// form is off, mirroring `buildPricingSectionContent`'s null-return
// contract.

function buildPricingPage(input: TemplateSeedInput, accent: string, fontFamily: string): BrochurePage | null {
  const cards = (input.pricingCards ?? []).filter(
    (c) => c && c.title?.trim() && c.price?.trim()
  ) as Array<{ title: string; subtitle?: string | null; price: string; discounts?: string[] | null }>;
  const showForm = input.showRegistrationForm === true;
  if (cards.length === 0 && !showForm) return null;

  const pageW = A4_WIDTH_MM;
  const pageH = A4_HEIGHT_MM;
  const elements: BrochureElement[] = [];
  const push = (el: BrochureElement) => {
    el.zIndex = elements.length;
    elements.push(el);
  };

  const bodyLeft = 20;
  const bodyW = pageW - 40;
  let cursorY = 20;

  // Top centered logo (white on the accent background) — matches
  // `drawPosterHeaderLogo` called from `drawPricingSection`.
  if (input.logoUrl) {
    const logoW = 50;
    const logoH = 16;
    push(
      newImageElement({
        x: pageW / 2 - logoW / 2,
        y: cursorY,
        width: logoW,
        height: logoH,
        src: input.logoUrl,
        fit: "contain",
      })
    );
    cursorY += logoH + 8;
  } else {
    cursorY += 4;
  }

  if (cards.length > 0) {
    const cardH = 66;
    const gap = 6;
    const cols = Math.min(cards.length, 2);
    const cardW = (bodyW - gap * (cols - 1)) / cols;
    for (let i = 0; i < cards.length; i += 1) {
      const card = cards[i];
      const col = i % cols;
      const row = Math.floor(i / cols);
      const cx = bodyLeft + col * (cardW + gap);
      const cy = cursorY + row * (cardH + gap);

      push(
        newShapeElement({
          x: cx,
          y: cy,
          width: cardW,
          height: cardH,
          shape: "rect",
          fill: "#ffffff",
          stroke: "transparent",
          strokeWidth: 0,
          cornerRadius: 8,
        })
      );
      push(
        newTextElement({
          x: cx + 8,
          y: cy + 6,
          width: cardW - 16,
          height: 10,
          content: card.title.toUpperCase(),
          fontFamily,
          fontSize: 13,
          fontWeight: "bold",
          color: "#000000",
          align: "left",
          lineHeight: 1,
        })
      );
      if (card.subtitle) {
        push(
          newTextElement({
            x: cx + 8,
            y: cy + 15,
            width: cardW - 16,
            height: 6,
            content: card.subtitle,
            fontFamily,
            fontSize: 9,
            fontWeight: "normal",
            color: "#505050",
            align: "left",
            lineHeight: 1,
          })
        );
      }
      push(
        newTextElement({
          x: cx,
          y: cy + 24,
          width: cardW,
          height: 14,
          content: card.price,
          fontFamily,
          fontSize: 22,
          fontWeight: "bold",
          color: "#000000",
          align: "center",
          lineHeight: 1,
        })
      );
      const discounts = (card.discounts ?? []).filter((d) => d && d.trim());
      if (discounts.length > 0) {
        push(
          newTextElement({
            x: cx + 8,
            y: cy + 42,
            width: cardW - 16,
            height: 5,
            content: "Group Discounts",
            fontFamily,
            fontSize: 8.5,
            fontWeight: "bold",
            color: "#3c3c3c",
            align: "left",
            lineHeight: 1,
          })
        );
        push(
          newTextElement({
            x: cx + 8,
            y: cy + 48,
            width: cardW - 16,
            height: 16,
            content: discounts.join("\n"),
            fontFamily,
            fontSize: 8,
            fontWeight: "normal",
            color: "#3c3c3c",
            align: "left",
            lineHeight: 1.4,
          })
        );
      }
    }
    const rowCount = Math.ceil(cards.length / cols);
    cursorY += rowCount * (cardH + gap);
  }

  if (showForm) {
    const labels: Array<[string, string]> = [
      ["Name", "Designation"],
      ["Mobile", "Email"],
    ];
    const cellGap = 6;
    const cellW = (bodyW - cellGap) / 2;
    const inputH = 8;
    const rowCount = 3;
    cursorY += 6;
    for (let r = 0; r < rowCount; r += 1) {
      if (cursorY + 26 > pageH - 20) break;
      for (const [left, right] of labels) {
        push(
          newTextElement({
            x: bodyLeft,
            y: cursorY,
            width: cellW,
            height: 4,
            content: left,
            fontFamily,
            fontSize: 7.5,
            fontWeight: "normal",
            color: "#ffffff",
            align: "center",
            lineHeight: 1,
          })
        );
        push(
          newPillElement({
            x: bodyLeft,
            y: cursorY + 4,
            width: cellW,
            height: inputH,
            text: "",
            fontFamily,
            fontSize: 8,
            textColor: "#000000",
            fillColor: "#ffffff",
            strokeColor: "transparent",
            strokeWidth: 0,
          })
        );
        push(
          newTextElement({
            x: bodyLeft + cellW + cellGap,
            y: cursorY,
            width: cellW,
            height: 4,
            content: right,
            fontFamily,
            fontSize: 7.5,
            fontWeight: "normal",
            color: "#ffffff",
            align: "center",
            lineHeight: 1,
          })
        );
        push(
          newPillElement({
            x: bodyLeft + cellW + cellGap,
            y: cursorY + 4,
            width: cellW,
            height: inputH,
            text: "",
            fontFamily,
            fontSize: 8,
            textColor: "#000000",
            fillColor: "#ffffff",
            strokeColor: "transparent",
            strokeWidth: 0,
          })
        );
        cursorY += inputH + 6;
      }
      cursorY += 2;
    }
  }

  return {
    id: `page-pricing-${Math.random().toString(36).slice(2, 8)}`,
    width: A4_WIDTH_MM,
    height: A4_HEIGHT_MM,
    background: { type: "solid", color: accent },
    elements,
  };
}

// ─── Classic seed content pages ────────────────────────────────────────────
//
// The four page builders below turn the same event data the jsPDF
// preview uses (sessions, speakers, sponsors, venue) into ordinary
// editable elements so the editor and the preview render matching
// content by construction. Layout numbers are in mm.

/**
 * Shared section-heading (bold black title + short accent underline
 * beneath). Mirrors `drawHeadingUnderline` in `brochure-pdf.ts` exactly:
 *
 *   - Title text at `(theme.margins.left, theme.margins.top)`
 *   - Font size = `theme.heading.fontSizePt` (NOT a hardcoded 22pt —
 *     Classic Editorial uses 15pt, so hardcoding 22 made the editor's
 *     heading ~47% larger than the preview's, one of the visible
 *     differences reported by the organizer)
 *   - Accent underline only if `theme.heading.showAccentUnderline` is
 *     true; drawn at `y + 2` (relative to heading Y, matches the
 *     `startY + 2` offset used in `drawAgendaSection`,
 *     `drawSpeakersSection`, and `drawVenueLogisticsSection` in the
 *     preview)
 *
 * Returns the Y-cursor position where the content below the heading
 * should start, matching the preview's `y = startY + 10` / `+ 12`
 * convention so section content is vertically aligned in both
 * pipelines.
 */
function pushClassicSectionHeading(
  push: (el: BrochureElement) => void,
  theme: BrochureTheme,
  text: string,
  accent: string,
  fontFamily: string,
  /** Underline width in mm. Matches the widths hardcoded per section
   *  in `brochure-pdf.ts`: 24 for Agenda/Speakers/Sponsors, 40 for
   *  Venue & Logistics. */
  underlineWidthMm: number,
  /** Content Y-cursor offset from the heading baseline. Matches the
   *  preview's `+ 10` for Agenda/Speakers/Sponsors and `+ 12` for
   *  Venue. */
  contentOffsetMm: number
): number {
  const headingY = theme.margins.top;
  const headingX = theme.margins.left;
  push(
    newTextElement({
      x: headingX,
      y: headingY,
      width: 150,
      height: 10,
      content: text,
      fontFamily,
      fontSize: theme.heading.fontSizePt,
      fontWeight: theme.heading.fontStyle === "bold" ? "bold" : "normal",
      color: "#000000",
      align: "left",
      lineHeight: 1,
    })
  );
  if (theme.heading.showAccentUnderline) {
    push(
      newShapeElement({
        // Preview draws at `startY + 2`, but jsPDF's `doc.text` uses
        // baseline-y whereas our newTextElement uses top-left-y — the
        // heading font's baseline sits roughly at `fontSize` mm below
        // the top-left. Positioning the underline slightly below the
        // heading text (`+ 2` from the text bottom) matches the
        // preview's visual gap between text and underline.
        x: headingX,
        y: headingY + (theme.heading.fontSizePt * 0.35),
        width: underlineWidthMm,
        height: 1.4,
        shape: "rect",
        fill: accent,
        stroke: "transparent",
        strokeWidth: 0,
        cornerRadius: 0,
      })
    );
  }
  return headingY + contentOffsetMm;
}

/** Builds the Agenda page's `"table"` layout — one row per session
 *  (time • title • speakers) as separate editable text elements inside
 *  a bordered row container. Returns `null` when there are no sessions
 *  so the page isn't seeded with an empty heading. */
function buildAgendaPage(input: TemplateSeedInput, theme: BrochureTheme, accent: string, fontFamily: string): BrochurePage | null {
  const content = buildAgendaSectionContent(input.sessions ?? []);
  if (content.rows.length === 0) return null;

  const pageW = A4_WIDTH_MM;
  const elements: BrochureElement[] = [];
  const push = (el: BrochureElement) => {
    el.zIndex = elements.length;
    elements.push(el);
  };

  // Heading with accent underline (width=24mm, contentOffset=10mm) —
  // matches `drawAgendaSection`'s `drawHeadingUnderline(..., 24)` and
  // `y = startY + 10` in `brochure-pdf.ts`.
  const contentStartY = pushClassicSectionHeading(push, theme, "Agenda", accent, fontFamily, 24, 10);

  // Column widths mirror `drawAgendaTableLayout` exactly:
  //   time = 28mm (fixed)
  //   speakers = max(38, contentWidth * 0.28)
  //   session = whatever's left
  const bodyLeft = theme.margins.left;
  const bodyRight = pageW - theme.margins.right;
  const contentWidth = bodyRight - bodyLeft;
  const timeColW = 28;
  const speakersColW = Math.max(38, contentWidth * 0.28);
  const sessionColW = contentWidth - timeColW - speakersColW;
  const titleColX = bodyLeft + timeColW;
  const speakersColX = titleColX + sessionColW;

  const cellPad = 2; // matches `theme.table.cellPaddingMm`
  const headerRowH = 8;
  const bodyFontSize = 10;
  const bodyLineHeight = 1.3;
  const rowLineHeightMm = (bodyFontSize / 72) * 25.4 * bodyLineHeight; // pt -> mm
  const gridLineW = 0.15;
  const gridColor = "#d4d4d4"; // mirrors autoTable's default grid stroke

  const maxRows = 12;
  const rows = content.rows.slice(0, maxRows);

  // Rough row-height estimate: session titles are the most likely to
  // wrap, so we size each row to hold the wrapped title. Estimate ~30
  // chars per line at this column width for a rough guess (matches the
  // guess used elsewhere in the seed).
  const rowHeights = rows.map((row) => {
    const titleLines = Math.max(1, Math.ceil(row.title.length / 30));
    return Math.max(headerRowH, cellPad * 2 + titleLines * rowLineHeightMm);
  });
  const tableH = headerRowH + rowHeights.reduce((sum, h) => sum + h, 0);

  // ── Header row ─────────────────────────────────────────────────────
  push(
    newShapeElement({
      x: bodyLeft,
      y: contentStartY,
      width: contentWidth,
      height: headerRowH,
      shape: "rect",
      fill: accent,
      stroke: "transparent",
      strokeWidth: 0,
      cornerRadius: 0,
    })
  );
  const headerCells: Array<{ x: number; w: number; text: string }> = [
    { x: bodyLeft, w: timeColW, text: "Time" },
    { x: titleColX, w: sessionColW, text: "Session" },
    { x: speakersColX, w: speakersColW, text: "Speaker(s)" },
  ];
  for (const cell of headerCells) {
    push(
      newTextElement({
        x: cell.x + cellPad,
        y: contentStartY + (headerRowH - bodyFontSize * 0.35) / 2,
        width: cell.w - cellPad * 2,
        height: headerRowH - cellPad,
        content: cell.text,
        fontFamily,
        fontSize: bodyFontSize,
        fontWeight: "bold",
        color: "#ffffff",
        align: "left",
        lineHeight: 1,
      })
    );
  }

  // ── Body rows ──────────────────────────────────────────────────────
  let cursorY = contentStartY + headerRowH;
  for (let i = 0; i < rows.length; i += 1) {
    const row = rows[i];
    const rowH = rowHeights[i];
    // Time cell (bold black)
    push(
      newTextElement({
        x: bodyLeft + cellPad,
        y: cursorY + cellPad,
        width: timeColW - cellPad * 2,
        height: rowH - cellPad * 2,
        content: row.timeRangeText,
        fontFamily,
        fontSize: bodyFontSize,
        fontWeight: "bold",
        color: "#000000",
        align: "left",
        lineHeight: bodyLineHeight,
      })
    );
    // Session cell (normal black)
    push(
      newTextElement({
        x: titleColX + cellPad,
        y: cursorY + cellPad,
        width: sessionColW - cellPad * 2,
        height: rowH - cellPad * 2,
        content: row.title,
        fontFamily,
        fontSize: bodyFontSize,
        fontWeight: "normal",
        color: "#000000",
        align: "left",
        lineHeight: bodyLineHeight,
      })
    );
    // Speakers cell (normal gray — matches autoTable's `textColor:
    // [90, 90, 90]` for the speakers column)
    if (row.speakerLine) {
      push(
        newTextElement({
          x: speakersColX + cellPad,
          y: cursorY + cellPad,
          width: speakersColW - cellPad * 2,
          height: rowH - cellPad * 2,
          content: row.speakerLine,
          fontFamily,
          fontSize: bodyFontSize,
          fontWeight: "normal",
          color: "#5a5a5a",
          align: "left",
          lineHeight: bodyLineHeight,
        })
      );
    }
    cursorY += rowH;
  }

  // ── Grid lines (autoTable's `grid` theme) ─────────────────────────
  // Bottom of every row (horizontal lines) — includes the top of the
  // header + bottom of every row + top of body.
  const tableBottom = contentStartY + tableH;
  // Horizontal lines: top of header, bottom of header/each row.
  let hy = contentStartY;
  push(
    newShapeElement({
      x: bodyLeft, y: hy, width: contentWidth, height: gridLineW,
      shape: "rect", fill: gridColor, stroke: "transparent", strokeWidth: 0, cornerRadius: 0,
    })
  );
  hy += headerRowH;
  push(
    newShapeElement({
      x: bodyLeft, y: hy, width: contentWidth, height: gridLineW,
      shape: "rect", fill: gridColor, stroke: "transparent", strokeWidth: 0, cornerRadius: 0,
    })
  );
  for (const h of rowHeights) {
    hy += h;
    push(
      newShapeElement({
        x: bodyLeft, y: hy, width: contentWidth, height: gridLineW,
        shape: "rect", fill: gridColor, stroke: "transparent", strokeWidth: 0, cornerRadius: 0,
      })
    );
  }
  // Vertical lines: left of table, between each column, right of table.
  const vxes = [bodyLeft, titleColX, speakersColX, bodyRight];
  for (const vx of vxes) {
    push(
      newShapeElement({
        x: vx, y: contentStartY, width: gridLineW, height: tableBottom - contentStartY,
        shape: "rect", fill: gridColor, stroke: "transparent", strokeWidth: 0, cornerRadius: 0,
      })
    );
  }

  return {
    id: `page-agenda-${Math.random().toString(36).slice(2, 8)}`,
    width: A4_WIDTH_MM,
    height: A4_HEIGHT_MM,
    background: { type: "solid", color: "#ffffff" },
    elements,
  };
}

/**
 * Session categories that get the "emphasis" black title chip on the
 * Poster_Bold agenda page — mirrors `AGENDA_EMPHASIS_SESSION_TYPES` in
 * `brochure-pdf.ts` exactly so the editor and the live preview color-
 * code sessions identically. Kept as a Set locally rather than
 * exported/imported to avoid a runtime dependency from the editor into
 * the jsPDF module.
 */
const EDITOR_AGENDA_EMPHASIS_SESSION_TYPES = new Set([
  "keynote",
  "panel",
  "fireside",
  "workshop",
]);

function editorAgendaRowBackground(sessionType: string | undefined, accent: string): string {
  if (sessionType && EDITOR_AGENDA_EMPHASIS_SESSION_TYPES.has(sessionType)) {
    return "#000000";
  }
  return accent;
}

/**
 * Builds the Agenda page's `"timetable-cards"` layout — matches
 * `drawAgendaTimetableCardsLayout` in `brochure-pdf.ts` exactly:
 *
 *   - Centered logo + huge "Event Agenda" title at the top.
 *   - Two chronologically-split columns (first half of sessions on the
 *     left, second half on the right).
 *   - Each row = colored time chip + colored title bar spanning the
 *     column width. Row background is BLACK for emphasized session
 *     types (keynote / panel / fireside / workshop) and the theme
 *     accent for everything else.
 *   - When a session has a description, it renders as a paragraph
 *     directly below the row on a white background with dark text.
 *   - Speaker line (when present) renders in small italic gray under
 *     the description (or under the title bar when there's no
 *     description).
 *
 * Every element is independently editable (Canva-style) — nothing is a
 * baked group. Returns `null` when there are no sessions.
 */
function buildAgendaTimetableCardsPage(input: TemplateSeedInput, theme: BrochureTheme, accent: string, fontFamily: string): BrochurePage | null {
  const content = buildAgendaSectionContent(input.sessions ?? []);
  if (content.rows.length === 0) return null;

  const pageW = A4_WIDTH_MM;
  const marginX = 20;
  const elements: BrochureElement[] = [];
  const push = (el: BrochureElement) => {
    el.zIndex = elements.length;
    elements.push(el);
  };

  // ── Top logo (centered) ──────────────────────────────────────────
  let cursorY = 18;
  if (input.logoUrl) {
    const logoW = 50;
    const logoH = 16;
    push(
      newImageElement({
        x: pageW / 2 - logoW / 2,
        y: cursorY,
        width: logoW,
        height: logoH,
        src: input.logoUrl,
        fit: "contain",
      })
    );
    cursorY += logoH + 6;
  } else {
    cursorY += 4;
  }

  // ── Huge "Event Agenda" title (centered) ─────────────────────────
  push(
    newTextElement({
      x: marginX,
      y: cursorY,
      width: pageW - marginX * 2,
      height: 16,
      content: "Event Agenda",
      fontFamily,
      fontSize: 30,
      fontWeight: "bold",
      color: "#000000",
      align: "center",
      lineHeight: 1,
    })
  );
  cursorY += 20;

  // ── Two-column chronological split ───────────────────────────────
  const bodyRight = pageW - marginX;
  const colGap = 6;
  const colWidth = (bodyRight - marginX - colGap) / 2;
  const timeChipW = 22;
  const titleBarW = colWidth - timeChipW;
  const rowMinH = 10;
  const rowGap = 2;

  // Split sessions into two roughly-equal chronological halves.
  const midpoint = Math.ceil(content.rows.length / 2);
  const columns: AgendaRow[][] = [
    content.rows.slice(0, midpoint) as AgendaRow[],
    content.rows.slice(midpoint) as AgendaRow[],
  ];
  const colTopY: [number, number] = [cursorY, cursorY];

  for (let colIdx = 0; colIdx < columns.length; colIdx += 1) {
    for (const row of columns[colIdx]) {
      const colX = marginX + colIdx * (colWidth + colGap);
      const cardY = colTopY[colIdx];

      const bg = editorAgendaRowBackground(row.sessionType, accent);

      // Row height grows with title length (long titles wrap to 2 lines
      // at this column width — ~28 chars/line is a decent estimate).
      const titleLineEstimate = Math.max(1, Math.ceil(row.title.length / 30));
      const rowH = Math.max(rowMinH, titleLineEstimate * 5 + 4);

      // Time chip (left, small).
      push(
        newShapeElement({
          x: colX,
          y: cardY,
          width: timeChipW,
          height: rowH,
          shape: "rect",
          fill: bg,
          stroke: "transparent",
          strokeWidth: 0,
          cornerRadius: 0,
        })
      );
      push(
        newTextElement({
          x: colX,
          y: cardY + rowH / 2 - 2,
          width: timeChipW,
          height: rowH,
          content: row.timeRangeText,
          fontFamily,
          fontSize: 8,
          fontWeight: "bold",
          color: "#ffffff",
          align: "center",
          lineHeight: 1,
        })
      );

      // Title bar (right, same fill).
      push(
        newShapeElement({
          x: colX + timeChipW,
          y: cardY,
          width: titleBarW,
          height: rowH,
          shape: "rect",
          fill: bg,
          stroke: "transparent",
          strokeWidth: 0,
          cornerRadius: 0,
        })
      );
      push(
        newTextElement({
          x: colX + timeChipW + 3,
          y: cardY + rowH / 2 - (titleLineEstimate * 2.5) + 0.5,
          width: titleBarW - 6,
          height: rowH,
          content: row.title,
          fontFamily,
          fontSize: 9.5,
          fontWeight: "bold",
          color: "#ffffff",
          align: "left",
          lineHeight: 1.2,
        })
      );

      let afterRowY = cardY + rowH;

      // Description body (below the row, dark text on white).
      if (row.description) {
        const descLineEstimate = Math.max(1, Math.ceil(row.description.length / 45));
        const descBlockH = descLineEstimate * 4 + 4;
        push(
          newTextElement({
            x: colX + 2,
            y: afterRowY + 2,
            width: colWidth - 4,
            height: descBlockH,
            content: row.description,
            fontFamily,
            fontSize: 9,
            fontWeight: "normal",
            color: "#000000",
            align: "left",
            lineHeight: 1.3,
          })
        );
        afterRowY += descBlockH + 2;
      }

      // Speaker line (italic gray, subtle).
      if (row.speakerLine) {
        push(
          newTextElement({
            x: colX + 2,
            y: afterRowY,
            width: colWidth - 4,
            height: 5,
            content: row.speakerLine,
            fontFamily,
            fontSize: 8.5,
            fontWeight: "normal",
            fontStyle: "italic",
            color: "#5a5a5a",
            align: "left",
            lineHeight: 1.2,
          } as Parameters<typeof newTextElement>[0])
        );
        afterRowY += 6;
      }

      colTopY[colIdx] = afterRowY + rowGap;
    }
  }

  return {
    id: `page-agenda-${Math.random().toString(36).slice(2, 8)}`,
    width: A4_WIDTH_MM,
    height: A4_HEIGHT_MM,
    background: { type: "solid", color: "#ffffff" },
    elements,
  };
}

/** Builds the Speakers page — 2-column grid of speaker cards
 *  (photo + name + subtitle + company). Each field is a separate
 *  element so the organizer can retitle or remove any of them.
 *  Returns `null` when there are no speakers. */
function buildSpeakersPage(speakers: SpeakerInput[], theme: BrochureTheme, accent: string, fontFamily: string): BrochurePage | null {
  const rows = buildSpeakerRows(speakers);
  if (rows.length === 0) return null;

  const pageW = A4_WIDTH_MM;
  const elements: BrochureElement[] = [];
  const push = (el: BrochureElement) => {
    el.zIndex = elements.length;
    elements.push(el);
  };

  const startY = pushClassicSectionHeading(push, theme, "Speakers", accent, fontFamily, 24, 12) + 2;

  const cols = 2;
  const gap = 8;
  const bodyLeft = 20;
  const cardW = (pageW - 40 - gap * (cols - 1)) / cols;
  const photoH = 44;
  const textH = 22;
  const cardH = photoH + textH + 2;
  const maxCards = 8; // 4 rows × 2 cols
  const shown = rows.slice(0, maxCards);

  for (let i = 0; i < shown.length; i += 1) {
    const row = shown[i];
    const col = i % cols;
    const rowIdx = Math.floor(i / cols);
    const x = bodyLeft + col * (cardW + gap);
    const y = startY + rowIdx * (cardH + 6);

    // Card background.
    push(
      newShapeElement({
        x,
        y,
        width: cardW,
        height: cardH,
        shape: "rect",
        fill: "#f9fafb",
        stroke: "#e5e7eb",
        strokeWidth: 0.3,
        cornerRadius: 2,
      })
    );

    // Photo (URL image) or initial placeholder shape.
    if (row.photo.type === "url") {
      push(
        newImageElement({
          x,
          y,
          width: cardW,
          height: photoH,
          src: row.photo.url,
          fit: "cover",
          cornerRadius: 2,
        })
      );
    } else {
      push(
        newShapeElement({
          x,
          y,
          width: cardW,
          height: photoH,
          shape: "rect",
          fill: accent,
          stroke: "transparent",
          strokeWidth: 0,
          cornerRadius: 2,
        })
      );
      push(
        newTextElement({
          x,
          y: y + photoH / 2 - 8,
          width: cardW,
          height: 16,
          content: row.photo.initial,
          fontFamily,
          fontSize: 32,
          fontWeight: "bold",
          color: "#ffffff",
          align: "center",
          lineHeight: 1,
        })
      );
    }

    // Name.
    push(
      newTextElement({
        x: x + 2,
        y: y + photoH + 2,
        width: cardW - 4,
        height: 6,
        content: row.name,
        fontFamily,
        fontSize: 11,
        fontWeight: "bold",
        color: "#0a1429",
        align: "center",
        lineHeight: 1.1,
      })
    );
    // Subtitle.
    if (row.subtitleLine) {
      push(
        newTextElement({
          x: x + 2,
          y: y + photoH + 8,
          width: cardW - 4,
          height: 5,
          content: row.subtitleLine,
          fontFamily,
          fontSize: 8.5,
          fontWeight: "normal",
          color: "#4b5563",
          align: "center",
          lineHeight: 1.1,
        })
      );
    }
    // Company.
    if (row.companyLine) {
      push(
        newTextElement({
          x: x + 2,
          y: y + photoH + 14,
          width: cardW - 4,
          height: 5,
          content: row.companyLine,
          fontFamily,
          fontSize: 8.5,
          fontWeight: "normal",
          color: accent,
          align: "center",
          lineHeight: 1.1,
        })
      );
    }
  }

  return {
    id: `page-speakers-${Math.random().toString(36).slice(2, 8)}`,
    width: A4_WIDTH_MM,
    height: A4_HEIGHT_MM,
    background: { type: "solid", color: "#ffffff" },
    elements,
  };
}

/** Builds the Sponsors page — tier headings followed by sponsor
 *  logos (or name text when no logo URL). Returns `null` when there
 *  are no sponsors. */
function buildSponsorsPage(sponsors: SponsorInput[], theme: BrochureTheme, accent: string, fontFamily: string): BrochurePage | null {
  if (sponsors.length === 0) return null;
  const groups = groupSponsorsByTierOrdered(sponsors);

  const pageW = A4_WIDTH_MM;
  const elements: BrochureElement[] = [];
  const push = (el: BrochureElement) => {
    el.zIndex = elements.length;
    elements.push(el);
  };

  let cursorY = pushClassicSectionHeading(push, theme, "Sponsors", accent, fontFamily, 24, 12);

  const bodyLeft = theme.margins.left;
  const bodyW = pageW - theme.margins.left - theme.margins.right;
  const perRow = 3;
  const logoGap = 4;
  const logoW = (bodyW - logoGap * (perRow - 1)) / perRow;
  const logoH = 22;

  for (const group of groups) {
    // Tier heading (colored by tier accent).
    push(
      newTextElement({
        x: bodyLeft,
        y: cursorY,
        width: bodyW,
        height: 7,
        content: group.label.toUpperCase(),
        fontFamily,
        fontSize: 12,
        fontWeight: "bold",
        color: group.accentColor,
        align: "left",
        lineHeight: 1,
      })
    );
    push(
      newShapeElement({
        x: bodyLeft,
        y: cursorY + 8,
        width: 16,
        height: 0.8,
        shape: "rect",
        fill: group.accentColor,
        stroke: "transparent",
        strokeWidth: 0,
        cornerRadius: 0,
      })
    );
    cursorY += 12;

    // Sponsor cards for this tier.
    const items = group.sponsors.slice(0, 12);
    for (let i = 0; i < items.length; i += 1) {
      const sponsor = items[i];
      const col = i % perRow;
      const rowIdx = Math.floor(i / perRow);
      const x = bodyLeft + col * (logoW + logoGap);
      const y = cursorY + rowIdx * (logoH + 4);

      // Card background so text logos have a distinct surface.
      push(
        newShapeElement({
          x,
          y,
          width: logoW,
          height: logoH,
          shape: "rect",
          fill: "#f9fafb",
          stroke: "#e5e7eb",
          strokeWidth: 0.3,
          cornerRadius: 2,
        })
      );
      if (sponsor.logo.type === "url") {
        push(
          newImageElement({
            x: x + 2,
            y: y + 2,
            width: logoW - 4,
            height: logoH - 4,
            src: sponsor.logo.url,
            fit: "contain",
            cornerRadius: 0,
          })
        );
      } else {
        push(
          newTextElement({
            x: x + 2,
            y: y + logoH / 2 - 3,
            width: logoW - 4,
            height: 6,
            content: sponsor.logo.text,
            fontFamily,
            fontSize: 10,
            fontWeight: "bold",
            color: "#0a1429",
            align: "center",
            lineHeight: 1.1,
          })
        );
      }
    }
    const rowsForGroup = Math.ceil(items.length / perRow);
    cursorY += rowsForGroup * (logoH + 4) + 4;
    if (cursorY > A4_HEIGHT_MM - 30) break; // stop before overflowing the page
  }

  return {
    id: `page-sponsors-${Math.random().toString(36).slice(2, 8)}`,
    width: A4_WIDTH_MM,
    height: A4_HEIGHT_MM,
    background: { type: "solid", color: "#ffffff" },
    elements,
  };
}

/** Builds the Venue & Logistics page — venue name, address, transit
 *  notes, parking notes. Returns `null` when there's no meaningful
 *  content to show. */
function buildVenuePage(input: VenueLogisticsInput | undefined, theme: BrochureTheme, accent: string, fontFamily: string): BrochurePage | null {
  if (!input) return null;
  const content = buildVenueLogisticsContent(input);
  if (!content) return null;

  const pageW = A4_WIDTH_MM;
  const elements: BrochureElement[] = [];
  const push = (el: BrochureElement) => {
    el.zIndex = elements.length;
    elements.push(el);
  };

  // Heading with wider (40mm) accent underline and 12mm content offset —
  // matches `drawVenueLogisticsSection`'s
  // `drawHeadingUnderline(..., 40)` and `y = startY + 12` exactly.
  let cursorY = pushClassicSectionHeading(push, theme, "Venue & Logistics", accent, fontFamily, 40, 12);

  const bodyLeft = theme.margins.left;
  const bodyW = pageW - theme.margins.left - theme.margins.right;

  // ── Field rows ─────────────────────────────────────────────────────
  //
  // Mirrors `drawVenueLogisticsSection`'s loop exactly:
  //   - Label rendered as "Label:" (Title case + colon), bold black, 11pt
  //   - Value rendered normal, gray (rgb 60,60,60), 10pt
  //   - Field order: Venue → Address → Parking → Transit
  //
  // Previous editor implementation used UPPERCASE labels in accent
  // color (10pt) with normal-black value (11pt) — visually diverged
  // from the preview by both size, casing, and color.
  const addField = (label: string, body: string): void => {
    push(
      newTextElement({
        x: bodyLeft,
        y: cursorY,
        width: bodyW,
        height: 5,
        content: `${label}:`,
        fontFamily,
        fontSize: 11,
        fontWeight: "bold",
        color: "#000000",
        align: "left",
        lineHeight: 1,
      })
    );
    cursorY += 5;
    // Rough estimate: ~90 chars per line at this width and font size.
    // Multi-line text auto-wraps inside its box in Konva, so the height
    // is just a container hint — a generous 24mm accommodates ~4 wrapped
    // lines without truncation for typical venue text.
    push(
      newTextElement({
        x: bodyLeft,
        y: cursorY,
        width: bodyW,
        height: 24,
        content: body,
        fontFamily,
        fontSize: 10,
        fontWeight: "normal",
        color: "#3c3c3c", // rgb(60, 60, 60), same as preview's `setTextColor(60, 60, 60)`
        align: "left",
        lineHeight: 1.4,
      })
    );
    // Match preview's `y += lines.length * 5 + 3` — assume ~2 lines of
    // wrapping for a typical field, plus the 3mm gap before the next
    // label. Keeps the editor's vertical spacing close to the PDF's.
    cursorY += 13;
  };

  // Field order matches `drawVenueLogisticsSection`'s textFields array:
  // Venue → Address → Parking → Transit.
  if (content.venueName) addField("Venue", content.venueName);
  if (content.address) addField("Address", content.address);
  if (content.parkingNotes) addField("Parking", content.parkingNotes);
  if (content.transitNotes) addField("Transit", content.transitNotes);

  return {
    id: `page-venue-${Math.random().toString(36).slice(2, 8)}`,
    width: A4_WIDTH_MM,
    height: A4_HEIGHT_MM,
    background: { type: "solid", color: "#ffffff" },
    elements,
  };
}

/** Builds the Sponsorship Packages page — a benefits × tiers comparison
 *  grid matching the reference "Premium Partnership Packages" deck
 *  brochures. Every header cell, benefit label, and value cell is an
 *  independent editable text/shape element (not a locked table widget),
 *  so the organizer can restyle, move, or delete any single cell exactly
 *  like every other element on the canvas. Returns `null` when there's
 *  no content to show (mirrors the jsPDF renderer's `buildSponsorship
 *  PackagesContent` null-return contract). */
function buildSponsorshipPackagesPage(
  input: SponsorshipPackagesInput | undefined,
  theme: BrochureTheme,
  accent: string,
  fontFamily: string
): BrochurePage | null {
  if (!input) return null;
  const content = buildSponsorshipPackagesContent(input);
  if (!content) return null;

  const pageW = A4_WIDTH_MM;
  const elements: BrochureElement[] = [];
  const push = (el: BrochureElement) => {
    el.zIndex = elements.length;
    elements.push(el);
  };

  const startY = pushClassicSectionHeading(push, theme, content.title, accent, fontFamily, 24, 12);

  const bodyLeft = theme.margins.left;
  const bodyRight = pageW - theme.margins.right;
  const bodyW = bodyRight - bodyLeft;
  const benefitColW = 46;
  const tierCount = Math.max(1, content.tiers.length);
  const tierColW = (bodyW - benefitColW) / tierCount;
  const headerRowH = 10;
  const rowH = 8;

  // Header row — benefit column left blank, one cell per tier name.
  push(
    newShapeElement({
      x: bodyLeft,
      y: startY,
      width: benefitColW,
      height: headerRowH,
      shape: "rect",
      fill: accent,
      stroke: "transparent",
      strokeWidth: 0,
      cornerRadius: 0,
    })
  );
  for (let c = 0; c < content.tiers.length; c += 1) {
    const x = bodyLeft + benefitColW + c * tierColW;
    push(
      newShapeElement({
        x,
        y: startY,
        width: tierColW,
        height: headerRowH,
        shape: "rect",
        fill: accent,
        stroke: "#ffffff",
        strokeWidth: 0.2,
        cornerRadius: 0,
      })
    );
    push(
      newTextElement({
        x: x + 1,
        y: startY + headerRowH / 2 - 4,
        width: tierColW - 2,
        height: 8,
        content: content.tiers[c].name,
        fontFamily,
        fontSize: 9,
        fontWeight: "bold",
        color: "#ffffff",
        align: "center",
        lineHeight: 1.05,
      })
    );
  }

  // Benefit rows — alternating row background for readability, one
  // label cell + one value cell per tier.
  const maxRows = 14; // keep the page from overflowing on very long lists
  const benefitRows = content.benefits.slice(0, maxRows);
  for (let r = 0; r < benefitRows.length; r += 1) {
    const y = startY + headerRowH + r * rowH;
    const rowBg = r % 2 === 0 ? "#f9fafb" : "#ffffff";

    push(
      newShapeElement({
        x: bodyLeft,
        y,
        width: bodyW,
        height: rowH,
        shape: "rect",
        fill: rowBg,
        stroke: "#e5e7eb",
        strokeWidth: 0.15,
        cornerRadius: 0,
      })
    );
    push(
      newTextElement({
        x: bodyLeft + 1.5,
        y: y + rowH / 2 - 3,
        width: benefitColW - 3,
        height: rowH - 1,
        content: benefitRows[r],
        fontFamily,
        fontSize: 7,
        fontWeight: "bold",
        color: "#0a1429",
        align: "left",
        lineHeight: 1.05,
      })
    );

    for (let c = 0; c < content.tiers.length; c += 1) {
      const x = bodyLeft + benefitColW + c * tierColW;
      const cell = content.tiers[c].cells[r];
      const label =
        cell?.kind === "check" ? "✓" : cell?.kind === "cross" ? "✗" : cell?.kind === "text" ? cell.value : "—";
      const cellColor = cell?.kind === "check" ? "#16a34a" : cell?.kind === "cross" ? "#dc2626" : "#0a1429";
      push(
        newTextElement({
          x: x + 1,
          y: y + rowH / 2 - 3,
          width: tierColW - 2,
          height: rowH - 1,
          content: label,
          fontFamily,
          fontSize: 7,
          fontWeight: cell?.kind === "check" || cell?.kind === "cross" ? "bold" : "normal",
          color: cellColor,
          align: "center",
          lineHeight: 1.05,
        })
      );
    }
  }

  // Cost row — bold, accent-colored, at the bottom of the table.
  const hasCost = content.tiers.some((t) => t.price);
  if (hasCost) {
    const y = startY + headerRowH + benefitRows.length * rowH;
    push(
      newShapeElement({
        x: bodyLeft,
        y,
        width: bodyW,
        height: rowH + 2,
        shape: "rect",
        fill: "#111111",
        stroke: "transparent",
        strokeWidth: 0,
        cornerRadius: 0,
      })
    );
    push(
      newTextElement({
        x: bodyLeft + 1.5,
        y: y + (rowH + 2) / 2 - 3,
        width: benefitColW - 3,
        height: rowH,
        content: "Cost",
        fontFamily,
        fontSize: 8,
        fontWeight: "bold",
        color: "#ffffff",
        align: "left",
        lineHeight: 1.05,
      })
    );
    for (let c = 0; c < content.tiers.length; c += 1) {
      const x = bodyLeft + benefitColW + c * tierColW;
      push(
        newTextElement({
          x: x + 1,
          y: y + (rowH + 2) / 2 - 3,
          width: tierColW - 2,
          height: rowH,
          content: content.tiers[c].price ?? "—",
          fontFamily,
          fontSize: 7.5,
          fontWeight: "bold",
          color: "#ffffff",
          align: "center",
          lineHeight: 1.05,
        })
      );
    }
  }

  return {
    id: `page-sponsorship-${Math.random().toString(36).slice(2, 8)}`,
    width: A4_WIDTH_MM,
    height: A4_HEIGHT_MM,
    background: { type: "solid", color: "#ffffff" },
    elements,
  };
}
