-- ─────────────────────────────────────────────────────────────────────────────
-- 022_event_creatives.sql
--
-- Creates `public.event_creatives` — records of rendered social/email
-- promotional graphics (speaker, sponsor, or combo) generated by the
-- Creative_Generator for an event.
--
-- What this is
-- ────────────
-- Each row is one successfully rendered PNG: which entity (speaker/sponsor/
-- both), which code-defined template, which platform format (LinkedIn post,
-- Instagram story, etc.), and where the asset lives in Storage. Template
-- *selection* preferences are stored separately on `events.page_config`
-- (`creativeTemplatePrefs`) — this table only records generated output.
--
-- Why NO anon/public SELECT policy
-- ─────────────────────────────────
-- Unlike `event_speakers` / `event_sponsors`, this table is organizer/admin
-- tool data, not public event-page content. There is intentionally no
-- "Anon view" or "Auth view ... USING(true)" policy here — only the event's
-- owning organizer or a platform admin may see or manage these rows, per
-- Requirement 9 ("restrict... to that event's owning organizer and users
-- with the admin role").
--
-- Storage
-- ───────
-- Rendered PNGs upload to the EXISTING `site-assets` bucket under a new
-- `event-creatives/{event_id}/` prefix. This migration does NOT create a new
-- bucket or new storage policies — it reuses the `site-assets` bucket's
-- existing `storage.objects` RLS policies already defined in
-- `000_full_schema.sql` ("Public read site-assets", "Admin upload/update/
-- delete site-assets").
--
-- Requirements addressed: 8.1, 9.1, 9.2, 9.3
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE public.event_creatives (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
  creative_type text NOT NULL CHECK (creative_type IN ('speaker','sponsor','combo')),
  speaker_id uuid REFERENCES public.speakers(id) ON DELETE SET NULL,
  sponsor_id uuid REFERENCES public.sponsors(id) ON DELETE SET NULL,
  template_id text NOT NULL,
  platform_format text NOT NULL,
  asset_url text NOT NULL,
  storage_path text NOT NULL,
  created_by uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT event_creatives_entity_check CHECK (
    (creative_type = 'speaker' AND speaker_id IS NOT NULL AND sponsor_id IS NULL) OR
    (creative_type = 'sponsor' AND sponsor_id IS NOT NULL AND speaker_id IS NULL) OR
    (creative_type = 'combo'   AND speaker_id IS NOT NULL AND sponsor_id IS NOT NULL)
  )
);
CREATE INDEX event_creatives_event_idx ON public.event_creatives(event_id, created_at DESC);

ALTER TABLE public.event_creatives ENABLE ROW LEVEL SECURITY;

-- Same organizer/admin-scoped pattern as event_speakers / event_sponsors,
-- minus the anon/authenticated-public SELECT policy (see header comment).
CREATE POLICY "Owner view event_creatives" ON public.event_creatives
  FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.events WHERE id = event_id AND (user_id = auth.uid() OR has_role(auth.uid(), 'admin'))));

CREATE POLICY "Owner manage event_creatives" ON public.event_creatives
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.events WHERE id = event_id AND (user_id = auth.uid() OR has_role(auth.uid(), 'admin'))))
  WITH CHECK (EXISTS (SELECT 1 FROM public.events WHERE id = event_id AND (user_id = auth.uid() OR has_role(auth.uid(), 'admin'))));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.event_creatives TO authenticated;
