-- ─────────────────────────────────────────────────────────────────────────────
-- 023_creative_ai_backgrounds.sql
--
-- Creates `public.event_creative_backgrounds` — cached AI-generated background
-- images produced by the Creative_AI_Backgrounds feature. Each row records
-- one PNG generated by Google Gemini Imagen for a specific event with a
-- deterministic cache key so repeat requests reuse the same asset without
-- another Gemini call (Requirement 6.1, 6.2).
--
-- Also adds `event_creatives.metadata jsonb` so the base Creative_Generator
-- can persist AI-background provenance (`aiBackgroundId`, `stylePreset`,
-- `promptText`) alongside each rendered creative (Requirement 11.1, 11.2,
-- 11.3). Default `'{}'::jsonb` keeps every existing row valid without a
-- backfill.
--
-- Why NO anon/public SELECT policy
-- ─────────────────────────────────
-- Same rationale as `event_creatives` (migration 022): this is organizer/
-- admin tool data, not public event-page content. Only the event's owning
-- organizer or a platform admin may see or manage these rows
-- (Requirement 12.3).
--
-- Storage
-- ───────
-- Generated PNGs upload to the EXISTING `site-assets` bucket under the
-- `ai-backgrounds/{event_id}/` prefix. This migration does NOT create a
-- new bucket or new storage policies — it reuses the `site-assets` bucket's
-- existing `storage.objects` RLS policies from `000_full_schema.sql`.
--
-- Requirements addressed: 6.1, 6.2, 6.3, 8.1, 11.1, 11.2, 11.3, 12.3
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE public.event_creative_backgrounds (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
  cache_key text NOT NULL,
  prompt text NOT NULL,
  prompt_normalized text NOT NULL,
  style_preset text NOT NULL,
  aspect_ratio text NOT NULL,
  asset_url text NOT NULL,
  storage_path text NOT NULL,
  storage_bucket text NOT NULL DEFAULT 'site-assets',
  media_type text NOT NULL DEFAULT 'image/png',
  width integer,
  height integer,
  size_bytes bigint,
  provider text NOT NULL DEFAULT 'gemini',
  model text,
  created_by uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz,
  CONSTRAINT event_creative_backgrounds_cache_key_unique
    UNIQUE (event_id, cache_key)
);

-- Fast lookup for library listings (Requirement 7.1): sorted most-to-least
-- recently created. Also serves single-column `event_id` filters via the
-- leftmost-prefix rule.
CREATE INDEX event_creative_backgrounds_event_idx
  ON public.event_creative_backgrounds (event_id, created_at DESC);

-- Partial index for expiry-based cleanup jobs: only rows with an explicit
-- `expires_at` participate, so the index stays compact.
CREATE INDEX event_creative_backgrounds_expires_idx
  ON public.event_creative_backgrounds (expires_at)
  WHERE expires_at IS NOT NULL;

ALTER TABLE public.event_creative_backgrounds ENABLE ROW LEVEL SECURITY;

-- Same organizer/admin-scoped pattern as event_creatives (migration 022).
-- Intentionally no anon/authenticated-public SELECT policy: this is
-- organizer tool data (Requirement 12.3).
CREATE POLICY "Owner view event_creative_backgrounds" ON public.event_creative_backgrounds
  FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.events WHERE id = event_id AND (user_id = auth.uid() OR has_role(auth.uid(), 'admin'))));

CREATE POLICY "Owner manage event_creative_backgrounds" ON public.event_creative_backgrounds
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.events WHERE id = event_id AND (user_id = auth.uid() OR has_role(auth.uid(), 'admin'))))
  WITH CHECK (EXISTS (SELECT 1 FROM public.events WHERE id = event_id AND (user_id = auth.uid() OR has_role(auth.uid(), 'admin'))));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.event_creative_backgrounds TO authenticated;

-- ─────────────────────────────────────────────────────────────────────────────
-- `event_creatives.metadata` — AI-background provenance for base-spec rows.
--
-- Existing base-spec inserts don't set this column; the `NOT NULL DEFAULT
-- '{}'::jsonb` clause guarantees every row (old and new) has a valid value,
-- so `typeof row.metadata === "object"` is a safe assumption in UI code
-- (Requirement 11.3, 11.4). Matches the shape of other JSONB columns in
-- the base schema (e.g. `events.page_config`).
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE public.event_creatives
  ADD COLUMN metadata jsonb NOT NULL DEFAULT '{}'::jsonb;
